/* C code generated by Lisaac compiler (www.lisaac.org) */
#define _LARGE_FILE_API
#define _LARGEFILE_SOURCE
#define _LARGEFILE64_SOURCE
#include <signal.h>
int arg_count;
char **arg_vector;

/*==========================*/
/* EXTERNAL                 */
/*==========================*/

/* SYSTEM_IO */

#include <stdio.h>
#include <stdlib.h>
  
/* Hardware 'print_char' */
void print_char(char car)
{
  fputc(car,stdout);
}

/* Hardware 'exit' */
int die_with_code(int code)
{
  exit(code);
}


/* SYSTEM */
#include <time.h>

/*==========================*/
/* TYPE                     */
/*==========================*/

/* Generic Object */
struct ___OBJ {
  unsigned int __id;
};

typedef struct li__U_struct __li__U;
/* NULL */
#ifndef NULL
#define NULL ((void *)0)
#endif

typedef signed int __li__K;
typedef char __li__3;
/* li__U */
#define __li__U__ 0
struct li__U_struct {
  __li__K li__VB;
  __li__3 *li__WB;
};
typedef char __li__C;
typedef void * __li__CB;
#define li__I__ 0
#define li__B__ 1
/* ___CONTEXT */
typedef struct ___CONTEXT_struct _____CONTEXT; 
struct ___CONTEXT_struct {
  unsigned long code; 
  _____CONTEXT *back; 
};
_____CONTEXT *top_context; 


void *table_type[1];

/*==========================*/
/* SOURCE LINE REFERENCE    */
/*==========================*/

#define L4642326 0
#define L9491990 1
#define L14341654 2
#define L19191318 3
#define L22038023 4
#define L19150865 5
#define L9848323 6
#define L2151958 7
#define L7001622 8
#define L22208022 9
#define L11851286 10
#define L16700950 11
#define L16780308 12
#define L15235591 13
#define L8782860 14
#define L4511254 15
#define L9360918 16
#define L22026759 17
#define L14210582 18
#define L19060246 19
#define L2020886 20
#define L6870550 21
#define L22076950 22
#define L11720214 23
#define L16569878 24
#define L21419542 25
#define L21906961 26
#define L4380182 27
#define L9229846 28
#define L14079510 29
#define L18929174 30
#define L10900993 31
#define L6300679 32
#define L13509633 33
#define L1889814 34
#define L6739478 35
#define L11589142 36
#define L16438806 37
#define L8530437 38
#define L21288470 39
#define L15501319 40
#define L4249110 41
#define L9098774 42
#define L13948438 43
#define L6031900 44
#define L18798102 45
#define L19285521 46
#define L9574915 47
#define L8260099 48
#define L1758742 49
#define L6608406 50
#define L11458070 51
#define L5005339 52
#define L16307734 53
#define L21903889 54
#define L21157398 55
#define L16785428 56
#define L4118038 57
#define L8967702 58
#define L13817366 59
#define L5900828 60
#define L18667030 61
#define L1627670 62
#define L6477334 63
#define L11326998 64
#define L21902353 65
#define L16176662 66
#define L8009219 67
#define L21026326 68
#define L322582 69
#define L22051345 70
#define L3986966 71
#define L6296071 72
#define L8836630 73
#define L13686294 74
#define L19282449 75
#define L18535958 76
#define L1496598 77
#define L6346262 78
#define L11195926 79
#define L15496711 80
#define L16045590 81
#define L9055261 82
#define L20895254 83
#define L21910545 84
#define L3855894 85
#define L21899271 86
#define L8705558 87
#define L19280913 88
#define L13555222 89
#define L6304263 90
#define L18404886 91
#define L10904579 92
#define L1365526 93
#define L21899281 94
#define L6215190 95
#define L11064854 96
#define L15914518 97
#define L20764182 98
#define L847382 99
#define L8663564 100
#define L3724822 101
#define L8574486 102
#define L13424150 103
#define L18273814 104
#define L19289105 105
#define L19428369 106
#define L1234454 107
#define L6084118 108
#define L10933782 109
#define L15783446 110
#define L20633110 111
#define L19277841 112
#define L3593750 113
#define L8443414 114
#define L13293078 115
#define L9706499 116
#define L18142742 117
#define L22474262 118
#define L1103382 119
#define L5953046 120
#define L10802710 121
#define L15652374 122
#define L20502038 123
#define L22153735 124
#define L3462678 125
#define L8312342 126
#define L13162006 127
#define L18011670 128
#define L11029511 129
#define L22153745 130
#define L22343190 131
#define L972310 132
#define L15231495 133
#define L5821974 134
#define L10671638 135
#define L15521302 136
#define L22691350 137
#define L20370966 138
#define L454166 139
#define L8260620 140
#define L12342789 141
#define L8270348 142
#define L3331606 143
#define L8181270 144
#define L13030934 145
#define L17880598 146
#define L16923660 147
#define L4724235 148
#define L21554710 149
#define L5690902 150
#define L9195015 151
#define L7481859 152
#define L10540566 153
#define L15390230 154
#define L20239894 155
#define L10241039 156
#define L19532305 157
#define L3200534 158
#define L6437404 159
#define L8050198 160
#define L12899862 161
#define L17749526 162
#define L22599190 163
#define L9452547 164
#define L14700551 165
#define L9990151 166
#define L5559830 167
#define L10409494 168
#define L15259158 169
#define L20108822 170
#define L3069462 171
#define L7919126 172
#define L12768790 173
#define L17618454 174
#define L14689285 175
#define L21949974 176
#define L5428758 177
#define L10278422 178
#define L15128086 179
#define L6962199 180
#define L19977750 181
#define L140310 182
#define L2938390 183
#define L7788054 184
#define L12637718 185
#define L17187852 186
#define L17487382 187
#define L8792065 188
#define L716822 189
#define L5297686 190
#define L10147350 191
#define L14997014 192
#define L19846678 193
#define L2807318 194
#define L7656982 195
#define L12506646 196
#define L17356310 197
#define L10652673 198
#define L5166614 199
#define L10016278 200
#define L14865942 201
#define L19715606 202
#define L6032924 203
#define L2676246 204
#define L7525910 205
#define L12375574 206
#define L17225238 207
#define L4985355 208
#define L5035542 209
#define L9885206 210
#define L14734870 211
#define L19584534 212
#define L21764103 213
#define L2545174 214
#define L7394838 215
#define L12244502 216
#define L17094166 217
#define L4904470 218
#define L9754134 219
#define L14603798 220
#define L19453462 221
#define L18378268 222
#define L6437916 223
#define L2414102 224
#define L174992396 225
#define L7263766 226
#define L12113430 227
#define L16963094 228
#define L21812758 229
#define L21772305 230
#define L581142 231
#define L4773398 232
#define L9623062 233
#define L14472726 234
#define L6556188 235
#define L19322390 236
#define L12081157 237
#define L152086 238
#define L2283030 239
#define L7132694 240
#define L11982358 241
#define L16832022 242
#define L21681686 243
#define L9989127 244

/*==========================*/
/* GLOBAL                   */
/*==========================*/

__li__U li__U_;
#define li__U__ (&li__U_)


/*==========================*/
/* STRING CONSTANT          */
/*==========================*/

__li__U __string_1={99,"console.log(\"@s=global[16640x i8]c\\\"HAI 1.2\\\\0A\
VISIBLE \\\\22x=string.gsub((:\\\\22changequote(<@,@>)\\\\"};
__li__U __string_2={99,"5Cndefine(p,<@all::\\\\5Cn\\\\09@echo 'linel::99999;\
print(\\\\5C:\\\\22solve satisfy;output [(&1&\\\\5C:\\\\22."};
__li__U __string_3={99,"assembly t{}.method public static void Main(){.entry\
point ldstr&3&\\\\5C:\\\\22m{{!:: x&4&nqr:: |-&4&n "};
__li__U __string_4={99,"::db`$$print(&15&\\\\5C:\\\\22printf(&31&\\\\5C:\\\\\
22\\#import<stdio.h>&32&nint main(){puts(&63&\\\\5C:\\\\22pr"};
__li__U __string_5={99,"int_string(&127&\\\\5C:\\\\22s=double(&255&\\\\5C:\\\
\\22print(&511&\\\\5C:\\\\22$$console::line[program QR^(out"};
__li__U __string_6={99,"put^)^;begin write^('&1&''s++_+^;s++chr 36+e^;s++,+^\
;s++chr 39+e^;s++chr 42+e^;s++B+^;s++chr 39+e^;"};
__li__U __string_7={99,"s++eval pack+^;s++chr 59+e^;s++eg+^;s++chr 124+e^;s+\
+,2+^;s++chr 41+e^;s++6-41+^;s++chr 42+e^;s++ch"};
__li__U __string_8={99,"r 41+e^;s++n/32+^;s++chr 36+e^;s++chr 40+e^;s++n-int\
+^;s++chr 36+e^;s++B8,chr+^;s++chr 40+e^;s++sub"};
__li__U __string_9={99,"str unp'&1&'','&1&''ack+^;s++chr 59+e^;s++chr 38+e^;\
s++chr 36+e^;s++ord+^;s++chr 61+e^;s++n+^;s++ch"};
__li__U __string_10={99,"r 36+e^;s++chr 124+e^;s++.+^;s++chr 124+e^;s++s+^;s\
++chr 59+e^;s++chr 34+e^;s++84wx8mFTDJkbD2xkO6/U"};
__li__U __string_11={99,"86cxAmgYRnoMP9Qc8Bkc7WVTLpxTLpxTLpxTLmY/Q1/x^::rAcT\
1/U71/U^::W/U76kdN5KLQL7u^::LRmOOscV^::fXSleLWCb"};
__li__U __string_12={99,"'&1&'','&1&''^::VKBVmsa49M8iaW0X7^::e8WGtePvccKsY1P\
m14Qq4t77OCQsO4ZcaCP11O75kUiWW8NLPAXBmCQGVZRgkcX"};
__li__U __string_13={99,"bQcEXotAWuNQXhbDPwiaL7vmbAcNLPA97tl93vYA1uNQXhiDR0Z\
DGoyQrjCnUJ1q2y9LQ8C^::37fDqsdhYIx^::HtnSsinWmjG"};
__li__U __string_14={99,"QpofWuq^::haEx^::Hs4R2ozWbhnkbGQR1hoe2hYNFuL0KsdQw7\
j^::bgl^::7xi9Uwpe1xhb6ZdNKlYX4AxcM'&1&'','&1&''"};
__li__U __string_15={99,"nQ3dHbCp3x^::Hs4R2ozX6hnkbGQEWiK3eUvIeAvbbFpQatyo9J\
KDGoy0K3gSbhnkWwcXo7eB6od9myQMGjK3WvPSaIjAbqySeU"};
__li__U __string_16={99,"vEnqCRmVHSO8ZPGt2dbBjjLtLQaaiYcl2DIAeDmsvX3GXnKxbQa\
4hTUCZX3Qxc/podrGvPqOyX3Mxc/dZeaZs7KRyMaxrP9KAH9"};
__li__U __string_17={99,"BksaldMruWMSxXdMlLcrAiJr8dfY8tfeJmQ2ohDUJmSrOXdJhm^\
::dMVOjX^::Q'&1&'','&1&''tlw0KdwPnpvhaoxPXrEQmvP"};
__li__U __string_18={99,"SaIivqrySrldT5xPNXpnKqYgAZpR4HrEMnpjKqNR9yEvPHlX8WM\
cPHpXCqsxNWaqRXpi9rMvQw8i^::1VeXUwq48Zm9LogRhyPN"};
__li__U __string_19={99,"auexpfDgrhxf^::S9Pq8ey6Fy/rv4RCSvEL0kSsyLamVYOLBkl6\
Zyph9PKdS9AKEvQmwi^::mwvQmwl^::rs9NTNpPLtj6a5Kxe"};
__li__U __string_20={99,"NyqaEk^::qQvQmwk^::rtoRqZXNGxbCrAjAWykCKxpTa5S'&1&'\
','&1&''Ta5vMa5wMLAjNnhn^::nAjTa6qdgxHQDBfTbZjRL"};
__li__U __string_21={99,"9e7KHD^::qSf7pFcNLtGNQFtTawSILIVNTIXEKdVS1lyMOfOxGB\
5YKEgTa5eqjIXEKBohHdyILIVNTIXIqCbNPIuTZ8Zl6bp7ph"};
__li__U __string_22={99,"4PetmTY4eMLVyqfl5YKFRemB0Oa4sCegXqFqKMyyaeHqLQt9OhS\
EuAXdgdqQ9sCVOZscmXbAnf61tmqHsAa7V95X4AaHs961tmk"};
__li__U __string_23={99,"JdCaYFaCWACWolCX9M^::CQ'&1&'','&1&''vtlpXvuOHXkJqDL\
8kKsdIQhdnMr8dQ6HqO5xrCbu^::Xkm9KfuValpyQDYxKWV8"};
__li__U __string_24={99,"PbEiR5xHGjakNO2N6OdMDGVkTh0kTh0kpHDEH5aW^::bFVtgGi9\
25KAXQgQ88HGWvzQ1VaPioxDWVk92AfYPlXYZe9^::H4yA6u"};
__li__U __string_25={99,"ZMtWrkA2/aqxWOjVoWY4kQ5ldMq6jdcdvca5iWjwVWbiOwtYcim\
4PXtSPmfjKnh9P/im^::MHfLY2RZ0Au9jLFyr^::SPRaxdj6"};
__li__U __string_26={99,"/ckO'&1&'','&1&''ZXb8fnaGX0TbPuvGaWN5yR^::ZeLWctXXa\
CgRWwDBWlqXUwq9NMvTLNjOKGexw5dMHhk96glCHQtBWkmBX"};
__li__U __string_27={99,"Qm5F/q^::0/l^::BsEAHYrCHMgAXYmCH3gXxmPPKw/jLs2Cm6XO\
QlyMaJb7LuDZsexR6vQhthBPk1xTUAuIy8yHJUuF5ZhvGliW"};
__li__U __string_28={99,"87OZsUgio5vHq8ey6ExXoBPA8EiHr1bIrHON^::ZYHtr99CX^::\
9I5vIqWFR2pvAXMgAlYsBGmmBmklB0YlB'&1&'','&1&''HA"};
__li__U __string_29={99,"gAHYqTHd5YLt4MNONvTe9Ea4nPIAQEp84d3MwD2kwEnmYEnl1d^\
::F37oCkC6RVqpxnPa4kQqVjR4xkbbNdNLQlY2FVNaFTG^::"};
__li__U __string_30={99,"F4FIF2F3R4Eo8/GJJ3YBthNKqFSIF1YBtTcfZoEYFAT3FGEY42T\
Y80Y2HAEIB0B481CIpdEoEwEIIPDYHDEYJ/EI7PEVh15t/oM"};
__li__U __string_31={99,"Qx2FI0yEWqoTYB0EqguErN0Er6eTYBDEYp0F0iKElh35o7PEidy\
EY42OXd1'&1&'','&1&''^::PFDEYp0F0h35oEPFidBHLp2E"};
__li__U __string_32={99,"Y41HN/rNMwoA1uNQboQElkg63EQA0l362EQDFkz62gQ11siLbEi\
xGsi95pj/^::ocOKpkYFxrMRhTQqtVQ6BcPrFTQ8tqOKJrAH"};
__li__U __string_33={99,"cuNaFTG2cc6KAcQ^::ZVPEM50UMd98tnRKlo0dUd95pZPN4t95K\
KS61F6qpZPN4tCWYcN54oMLsuLX/sLjhSypvvX2eM90pX9AJ"};
__li__U __string_34={99,"kYFxTcfYT9Kaz^::UqWpEMi2O8yA/Mi2O^::J0Ws'&1&'','&1&\
''BcbskvQlgTX0yN68jQ8W9CaAxELBX95AdCYZavHonBXd5Y"};
__li__U __string_35={99,"SoxA4FjpH3ugJQcGNRXTYpjj2AgELBX97xncnkzS5pgXowxc6P8\
quPiAGskWsdxDnswDrVhP1qDZYaXcbaxQqVZNLG9TLtoSL0Z"};
__li__U __string_36={99,"vetsR1xsQqm^::O8tavUAiS6BgR7gzDXlsQqkuXoYfHrpyS5pgP\
bAuS6BgvaVoR6/u^::mxrRrQiRnAiYKQjAQAt^::v/sIokjJ"};
__li__U __string_37={99,"6^::OQtdhWnswS6BgCa'&1&'','&1&''yRmedZ1axYvetsR7gjD\
XmDJOBsQqkufapkl9u9TOdVR8bi^::sgyDAxPEoF0J34PXth"};
__li__U __string_38={99,"nsbuLQskgPWZOs7mGCdept6GKv5tyKfBNqHdilFybj6DWCdTKJZ\
jGaoUgajxocsxtcuKLWZt7SmpxSrFsR6pv07c1v1p40sg3ne"};
__li__U __string_39={99,"5PRyBcTY4YMGtIlLFTGKwvnKxXNE1STb4mhPhWNKQVTY4YMGtIl\
LFTGKwiI8qnXkmPzRevEWV1RT^::89NDxqfhD95uQY'&1&''"};
__li__U __string_40={99,",'&1&''o7uMKFY938tfWUfTf7syNVxYzrOQtNyZrPtb8BD91gc^\
::zZyBXEdAH/r9NBD95suPKywBXEdYoxyRbqHzRevF1Vib5a"};
__li__U __string_41={99,"LDDZyB8mL9mUeTXPt9HYdrbpvONRiCaxYN1pkb3Ec^::TZyAmaH\
6X7rThuH6XAqpH4xSoEc^::zZyAWaH6gRyrdASrbsmA9VxYz"};
__li__U __string_42={99,"rOipAcEbLmmRPGXZRPIpFGGIt6ShRyAX7q9xIpAmlVprcfpHMq^\
::5^::LMEuKAftu9xKT^::5DL'&1&'','&1&''MUssjbcfpH"};
__li__U __string_43={99,"Mp^::0yXXkmPMwFnikBvgIlyRaxdN9dV7GVHGeZVb53xhsd7okH\
GWaZhQ^::phdrGeMG57YVeLW2/c9HpOje59EYJ6GItvKfSP/"};
__li__U __string_44={99,"im^::XtiLQtlHSO8ZPGtjbGtOs88xQuAnC2Ye9XMfB2EeBWjvQ2\
Ep9WmZlaAuhy1X7m4XP6JYNHldPu9SMKoyYw5eZjSWN2cuMq"};
__li__U __string_45={99,"yRD2mraqD3QvhEQaxbQa4hSv4ATbNjOPlBxv42gp4p7KJyIaL3S\
Lt'&1&'','&1&''2Pz8ZNTKfGKtbbaFddrFnxRb5kPIxCHhd"};
__li__U __string_46={99,"oHmmBXgdgIDfWbhdTLtbvK6mNG4ZTbhdTOjNgICneopZ1axYxRa\
OwtYcaPbhyfSP95Fj1r4PQmX3SbYhMq30WYZ3FItIGIN8Eo4"};
__li__U __string_47={99,"IGIxCZbt3GJN8IoZDHWu9WZ0GHoRGEIohGIEiTUAiWcdEIYx2FI\
FJIYJyF3ZKGJB8Hosim3F8Ip0AEP/tLGXzQ6sX90WUk6vIWW"};
__li__U __string_48={99,"Uibb23MqJyXX59p7e9pBGhWh'&1&'','&1&''Gh98sh1r4y7sci\
Sn3gB2JxWhPGWWVaDGVi9GoyEL8mMLYcPV3IOawVTchNWt7B"};
__li__U __string_49={99,"Qqyx^::aljNxCCQyKDJZiVamV7^::KkVNRPGWaZhQ84oTe8Y^::\
e8YONNjCrNjOKGexoUcd7yPPKI9PvlBxpccEBMAWjG^::LL0"};
__li__U __string_50={99,"PXsd8Hmv9QvuVamXB7KByph99YzwV94wd^::HuHOKwuNYWD295^\
::KaNigsf79kkzjceCPr2jdjZjSLZrQa4kYsuCYsuCYw5exw"};
__li__U __string_51={99,"dnhsc1v'&1&'','&1&''7g3ndhyCbt01BNb9XZxc2hyCbt1TY37\
c4RGGJF491cg9Wa^::c34yCrsuZbt2TY8yJ^::/tI3I7c7g8"};
__li__U __string_52={99,"IbsvTXdyF6tHc^::431LtHLe0OThEc8UZyIpuUXx9PKhPGWbDLH\
tr9JAJoJLD8988LQaaiEKlgs1mrapdaph7AZscifapkl9vJY"};
__li__U __string_53={99,"sxYx/hoTZe9^::OJOWmiVar/LOq4bNOdV7HhdPL1FR7daPLGZ6K\
CexqNhR1tEQg5ran7nBXdeCrglAHYuOHiK'&1&'','&1&''S"};
__li__U __string_54={99,"n7kBaYhCaYv^::hswSnQl9rpvKqZRLhsh9bpdNbqCTHdoCsfANt\
6XPSk2Cm59Kn3tBJpPAHQnLR5^::MqZjhKrBOTynWsckAHAl"};
__li__U __string_55={99,"B259R7cjgX3nAMdoTXMeWWwlCX3tAHUlBH3uDnwqAXQlB23n^::\
nExAnMmBXOm^::n7jAnKzBP7lBGykMH1kMH0GWbHKodhuDKt"};
__li__U __string_56={99,"ZRrteMLNV^::dpdP1tuOL/iFv0VGJ0DbQdHR8tVPGVHSO8ZPGuK\
PtqGSWt7osy9zm3'&1&'','&1&''xmZDxje59MwFnikBvgIl"};
__li__U __string_57={99,"y6KDjdefrPaJfPmtAOK7iKfSPnKxXNE1SeZUvORRXpx0npvSP^:\
:aD3QvhksaldMrs2YmtnRL28TcyAJ9BeMLNV^::qZj^::p0m"};
__li__U __string_58={99,"kJBoba4hWbqH^::apZ1aywgImeMG3cKomDIuBeMLNV^::wFiNmx\
HWbp9CmZKTXhRYmtgOKrXTe7LW87OZsVfTX9KYqRZR98VvqB"};
__li__U __string_59={99,"yXpBxSO8ZPGxjbLtAgJEvYqlYMrvKodhXl6Cv/rilH6tqPq'&1&\
'','&1&''ZYea3V94B9eLOQIofheHpiNLRyIodPkwAtq6aXf"};
__li__U __string_60={99,"6cxSGlncsxuDLEx92/i^::b7xQHqmBVHzQ6hwPblPPWmdrq5XdK\
7x^::HtiSq3wD1ViXXQs9nIp9MssB1goAfMcap/xSn/uWpgf"};
__li__U __string_61={99,"eJrZPHe^::91UfeGa^::9mV2czEB56KKMrGFWpqh9vud9TElAMh\
RWfP5IjdyEXrHnuZ/nwydE9ZPeJp/WmgcEOCdx5NdP5m^::L"};
__li__U __string_62={99,"OoCE1Wd9uYdx5OaR5BjP85^::LGWd9'&1&'','&1&''I/c9xAlA\
KImABofeGboQr0gsshR99YdE^::t09oACottoRL8iTjtXML0"};
__li__U __string_63={99,"ZrGUdgmh09xrR^::bBkP5b^::Wo1^::aAN4ybt3DKJqn1V6vhAf\
EZhGLGi^::9piK4ciMI4hIDIFPFJpRDJ0PJ4oJFkvojYIfm4"};
__li__U __string_64={99,"qZlYTiKyJ1DR2FEXknBXgdI4h3DI7iR5xHGWUnBWZRDI7wAH/z9\
3QfvWjD9ubR9shRWndEKoFR4Mcc9xCyEWj7aDFoPsgf99Yfe"};
__li__U __string_65={99,"GayEkvoPa4h'&1&'','&1&''NMhRLRAnBhqZEGgxEkvH2LBjjGt\
gPqQcsTtXML0Z9BGZlYLuTYQxhscRea3V953uENNmQa4tD4B"};
__li__U __string_66={99,"9DdlO095Pr1WGMGWQxWgxumU1v1pi0n4wPvkhEKty^::LFpALsh\
RWY6Ad9qMLu9IzXjdd2SwqH89qtVPKLL/nhHyCyaIC8gOKAh"};
__li__U __string_67={99,"zm3w^::GWUAR0ovcy92LBjjGtgPqSyne5PEBlbP5xWn4iDOHocr\
8iErY48pGsmYpN8IoZ1H3JypcdsDLB9kcx'&1&'','&1&''K"};
__li__U __string_68={99,"Ku59aRdbNL5KRKyi92l/^::3/y9NBYNKMVNGVk^::2l/XsfAP2e\
HM6F//im^::Xkm9P14ZP2f2knYvKfS9QqxgRaLqMSxnNbYvP"};
__li__U __string_69={99,"tr9TZiramtVQkhhMaltTbFvTGthNEdjj^::4ATbNjOPlBxmubzL\
ZkPw4yP5EMph99PLhvnndyS8BlQXdyT1qHTXdYMeGDobCXX4"};
__li__U __string_70={99,"erWZdahscXOKpkYLEwcaFdPmtcDdODHbr0ejT9QvS9KZxnGfuVW\
hlYPy9xhsdOhs'&1&'','&1&''eA2LBjjHdg7R9DWf4395yR"};
__li__U __string_71={99,"md8WNKQVTYUcXtQcQ9BZRgmZaslTcsw4RXpmQ4i9X4zi08gwDr0\
cQ/RuDHAfX6Qx55mbuxk3cMccXnxT9X3lTGY/Q6sx^::rAcT"};
__li__U __string_72={99,"A2/1A0yT1ZYNNQ3Wb4mCWp7okHGWW6XSmCKStSPKhBXMLGnrNCO\
vTe9WWtePm3cKsC7YVeLW7Y1v7hnMLZyWsiCQsi^::Wui9Xa"};
__li__U __string_73={99,"lyabtgyfQA27dZRgmAr7tl9^::4n9OkzWxUzWpqI^::'&1&'','\
&1&''bBkPCCneuoKCZfHQXpamWWNiGWCN8W^::Xd4Y95CMYp"};
__li__U __string_74={99,"fHtuihrGDcBdm9KaOD27lH^::2yCrsecTMfMDsiIrGugEdGQCLs\
rSwKNTU0kpLuKqfkrCOdpP6uzTa4YjAKNTX9pN5ZqTXDJTb8"};
__li__U __string_75={99,"jP5lyiwKNTX^::uNAJylNZymhLqsbs/Q6sqTaJlSn6qsbpdNbqS\
QDBoTfgxTb0jQ6tkPr0xaglgTXpyQLLXWZqI9GcnCk8jWZts"};
__li__U __string_76={99,"C2ZEHYRSQehSS24VeuKA'&1&'','&1&''POCZX6GXLbVXA4skLb\
XmdQOAOHohAHjFX5YwgXUeX6cvX5oiDMlX^::GozurQhX5AJ"};
__li__U __string_77={99,"ZcldDclu9GMaX5YjX6cwuqAwX6QzYKHfQpgckGbfMmwn9FMuX5A\
h^::Msn9n7dDsk0AZoiX/5AMssnXX8R^::ck0X5CCApouWZs"};
__li__U __string_78={99,"kLX0SA7cuWZskfMlXDMldXcluCtfnaGWtQa4tgoaErYFGWWtk4q\
inHYt2JemARmgm^::^::7s^::2UgAiW9GIF0J7ciNrdXPqpk"};
__li__U __string_79={99,"bbB'&1&'','&1&''nuqrcWYZ4HYGhMLCAN1Y1v6/LOvBCEGdCf0\
VgdyhY9NMh5MlY^::5BmMvzfN1aG9Q81^::7eEBqOh^::2y^"};
__li__U __string_80={99,"::Z7gvQndb^::ptsBqMjKGwvKURTf^::7s^::WsmC2TwQuCALys\
30KAx^::zFNLGyIWniAPXqzCsnQWkFq^::5CIWniAr8/rzbg"};
__li__U __string_81={99,"i^::bpvX53x3XiAMXqNQWUh^::Mli8UwpYd/rzWyAMWyAMGxbCr\
pZNnhOdS/fHWcc^::LAiqrdZXXOM^::i4k4qinEWehKn0RkW"};
__li__U __string_82={99,"'&1&'','&1&''wiSnNx^::maKSqsx3WtoPpxdTX7v91Vi3HEd^:\
:n7q9XMfPWgoBlGNQeWZQrkiT7liDN4Y3XhnsVVysL/LOmV1"};
__li__U __string_83={99,"C1mNQcli^::Q6fPWyz9Gcq^::HElu28wNKQvNLPATb/LOsh19iK\
ALlFnMxcc^::phy^::1ouEGpuLGhw91sd^::tlkcrDFXsklD"};
__li__U __string_84={99,"seNQbuDX23iYKFx9qK9CV7fDmiqjb1qQCUlbAWlQyK9e7jRtmu9\
kWxPCXgc9NNR^::tkzg5If3eVRWhxlRSC9r'&1&'','&1&''"};
__li__U __string_85={99,"rExPbJhAaBZP5kcMiEl^::KBZOKnU^::n3n9N9OySEuCKoxSvOO\
hSEuAHElNXp/96UgSGli9NtkzwjoHqxfWruNiGVs9Lu^::TY"};
__li__U __string_86={99,"xjOshyaPYcSGZyWru^::q4glTa4WQmVi9JqGPGVd9HpPZrcxB2M\
gBXAgPWZyZr3xSWocOHklAmYeAHAgQGld^::H3n9LuLAnAgS"};
__li__U __string_87={99,"Wkl9LuLBXAgSWli9TnbZXj^::S2pWDHpi9Hph95FdNdRPADMcS1\
YK3HCGtnhOZsiCXbDZ'&1&'','&1&''R6guTGa9LJofIeW9Z"};
__li__U __string_88={99,"8C9rseId8ByNqljMglyLu9tR8ByLu9t6qpjRbtZN6UgXrAiqrdZ\
TNCePrNyy6UgW87OZsVhYudjRbtZMbUgANCePrNywrUgB8By"};
__li__U __string_89={99,"kLumC8CePrNyNK8s^::21HeaxqTjBs^::25HTg4ygXWHS2dyT8B\
ye6hvSr4mTNOcWdG9MwlgTbNjOPlPPLBXYKldMZqDEme9CXe"};
__li__U __string_90={99,"9TS099NtoTGaIz7fTQLJdmt9gDslRkXy^::bAVSWsi9e7i'&1&'\
','&1&''9TI/y9NBkWhUz8Wkz8dEgWmMcXaEf9GPZ6KDjdi/"};
__li__U __string_91={99,"dbbFpQavqGWuSQBBNtLGaRKpWmS1Mtt8O96UdWg7jKne9LGwgWX\
dSA9pxWdCEB58IYBukC39kCIJyEf/tFNUiqtNuNF4xS^::Is"};
__li__U __string_92={99,"LKDKQw7jKxGHM6FR^::tm9LcskAf/sWcsG^::d4Ye4vvWaHsl8s\
5EAdn95Ys9WZYNKMVNEN/PTSCAHpXn5k5EAdn95Ys9aRZffp"};
__li__U __string_93={99,"hdrFkzGVPXqZxS^::Isq4iDOL'&1&'','&1&''pshHVR9Y/4OPx\
y35azTX1MbbE5TX0x9RUz7pr1DyKPWwX7a6q^::CwMcOHrEO"};
__li__U __string_94={99,"HmASmBohaaK9nr29N8YPnhsDMlv6sldCgCqMLu9p7lvS1wjKpZS\
M7dR^::pZSA6rI^::Zcvc26EN9NZCq4yqOJk98ly/ikhPUQl"};
__li__U __string_95={99,"CvOLb6uOTbXu0rhnKmfTN5wvQ/QnCwMcOXqAAXhe^::Gov9N8YP\
nhc0n36S/ReCqGaNHhYdaIvhb0yOpuYCqUcb6tkTZuYX6glC"};
__li__U __string_96={99,"ckcu'&1&'','&1&''n7yDckn8X5MCX9qhVtfOqZyBru^::Y8OTd\
6CYd6CYd6CYd6CYd6CYd6CYd6CYdBi^::CxkcYa4yWo46^::"};
__li__U __string_97={99,"N2S^::N2SFbYiGKl3DHovDKdYP34tDHgxOalYP6FgN5loP6hgEL\
JgELYxObFgP5FgELZ5SHozDKdYP34tFoNtFbZ6AY45SHtuP3"};
__li__U __string_98={99,"45FY82OalYFrZ6FbYyFoNt^::Y46SHp6DHpiYBsxDKtgP5F2DKd\
/DKdoP5lYP6FgN5mKENolAMgvO1WQTb/6'&1&'','&1&''Sn"};
__li__U __string_99={99,"3uX1Uc9CgmXXUn^::H3k9Hsy91Um^::Mkn9Gcma7soa2clhfNax\
ahdLeFyAmZRZ6txWdEdEGiXWmjDeGi^::jYQiaPZ2PqFZEQh"};
__li__U __string_100={99,"446FjIoccAHOGlY3fcxEibb23MqIc^::sgfnuYfWmxb^::BGCp\
8UdrGUdf47xo47wCHhGoGZ0DI3ibb23MqIc^::sgi9Xy^::^:"};
__li__U __string_101={99,":qQg6KDjdWV1b4GKDOYvlYLYCo8PFF6w9JEiQ6JnO1VEKo8PFR\
4RLN9SR6JmPbtI^::adj7RA'&1&'','&1&''frLqG2LBjjGtg"};
__li__U __string_102={99,"PqTHm1h09sj7a0FWSOtnSrliT67gSXpuKqtR4GVWKr7jBnXwMZ\
hmz63wbnUn8WNuKqtRDJhl9yEgeTk0PVOqMZhm^::nQsz58PQ"};
__li__U __string_103={99,"dGZkPIx35sx363xoAMvoKswgXMv9KBPPZqXjWWNiGZiCwMvZaY\
wXq3iqrdZhdllDL3eBnUfs1uNiI6^::W87OZsVd9GolAmaCC2"};
__li__U __string_104={99,"EvONRdoMsmDX1QSHplD5szMphlLHdtCqBPPh4RDLcfSGuNiI'&\
1&'','&1&''6^::A88HSO8ZPGtjbGtO96cxMphlLN8lDR1ce1"};
__li__U __string_105={99,"aIWdAVRaxfNLNdQbFpn6ulJ1xOP5scH7xHTIcv9JOHbbFpQauH\
^::iSeNEdjN1YfHhx7goFD^::23w^::GC94GdnYbAzRqVdjLt"};
__li__U __string_106={99,"opt4Y98NhPrNZ925MN5xvOGjLAHhppmpdCqJqmLZyA6HgBqFjS\
rLLRGcm9rGCAXho^::xQmhYWnI3l4EJB4fJscOMso^::nCGG^"};
__li__U __string_107={99,"::B3HmklIpJ17scJOFK9D1oXWVIc95AhR'&1&'','&1&''GaC2\
nMdYaDLRHiqG^::BEH3J0IoJGFI43HpJI^::25fI3l4EJB4Fo"};
__li__U __string_108={99,"ZKFJJEqSQdruW9LGvx92yyEWm9nt/rNOpxWmvxot/rNQzZWpZU\
RTgmAciK9K5vMbaieN8u^::aBgPkgca8G9SsdLWcdrWY0epGg"};
__li__U __string_109={99,"uOZshpH3sXX3f9bqCWWwnBHKmB23qBf86BX3tAHB/CQQjAHR0A\
nAlBH3nWbG^::qKNdPRrTTGbMEdGH^::iSiPL23fekqANm9Ka"};
__li__U __string_110={99,"ulItC9TGkzXZqI'&1&'','&1&''WdBlRSAdZ882P5w^::IrGSM\
KrUYZ4JGJEvWdGhZ903JJ0yEEWUF3zJA6t8t1mU^::bt2IbtH"};
__li__U __string_111={99,"c8MaEGka1EWUAH2/kA02HotIGItJFEZGTZBSc1N09Jug8UZyA6\
t3Hrt119/aaPYc1IxJHZE7192c8cg8IbtAHoxETZBSc1PIp/Z"};
__li__U __string_112={99,"yIu1bj^::431Lt0190HJ3xE1J8yEEWUFIt31J8yEf/tFLsvTYF\
yu3^::MDwxRkXzZasj7m8VxWsfTTMf1DseQWscn5QV'&1&'',"};
__li__U __string_113={99,"'&1&''xkYuQWtO9AF27TGgzf2yCLGi^::Tce9fMjMDt/rNNEiW\
dG9a8FRQDG^::LL0lWdHNTGZxd88xWdG9a4r1DuEgWZZsbuog"};
__li__U __string_114={99,"WsyLtRpxWtEdWdG9a4iUk6tScBEiWcdHJ3xETZ8JHWu94ZocKa\
li90W9PTtnMKRZ94BIEJFJIrtScA2/WWUibb23MqIc^::dtkl"};
__li__U __string_115={99,"5BZ90Xq9MdNWcdNKOq9p7e9KRGhWdNSfMeMa1uSRgY^::Z1alE\
yi9I8rhMT8Z7KJySmX09K'&1&'','&1&''BxTg4jgIPpqP42g"};
__li__U __string_116={99,"oldQLJdNbalFzJEPrJmgIRykSk9NLtWMKgVNrtYOLBcxOhHmLN\
Zin6pqOUdrroj9Wce9Wwj9Wce9WyZR2pvha9XdImXdKsxOHrE"};
__li__U __string_117={99,"F2ohDatvH2kw95sfBX7dXXYm9nApCoGqQmtWSOtnSrlXT5syA2\
xi^::SEu9/4XZZox9/4XLFKd48tey6FvT5dwOXld^::HApbvN"};
__li__U __string_118={99,"sDOYv/KBR^::jxkSrleT5gx92/i^::XYk45MVN6hwOrliPrHqK\
'&1&'','&1&''qYF9qhRDHpnKqcfOtEJCH3vOnso8WNsD2m7Y"};
__li__U __string_119={99,"VeLW4hf^::5fTS2ps^::jxs9HwcPWleDLUvS2pW^::hhuNHgcR\
HpPS1knknZR^::aoVCoFPRMssBppPRGwsBzlAD2lWKl0pz58P"};
__li__U __string_120={99,"36JRcuJs^::Hpp9LRcOPpyS2vES2ooyn3fOGpeCoFPS8OCC2RR\
KrUjC2RRKqshBFMuMXkwMng0MpofDJhd9yHTWWAVMqlpN5Iwc"};
__li__U __string_121={99,"aFdPmtcDdCNiGdkDPRAZ1lnKwD2kxUe'&1&'','&1&''QHpnCw\
5exw6t^::5ovlXgeQ2iQPXoc9b/hBGaCCH7f960PAJohBGaCC"};
__li__U __string_122={99,"H7eC2QvQ1gxAXhdZqsyAwAt9QNhDGUeQB3hBGaCCH7fBXhh^::\
GovQR3d9b3xQJgoyn/hPjlZP/hylXhi^::Gov9GdloHqK9b2F"};
__li__U __string_123={99,"Crr9Qy/dXp9cfNGQQmiXyqQgdQNht2hhD/wqCqoeDH7dQmiXyq\
Qg5Hey95AjPMsmDX/zWXECCceh9umZZrCGQuANCWmZTNRn9rC"};
__li__U __string_124={99,"GlaAuEa3'&1&'','&1&''^::BXEiNqJoFDVjNAYc45HsPqFZgq\
hVEJ84IYKkC1x8A34APXBiBKJaBakjI6cs9qNiSXIs^::o8DN"};
__li__U __string_125={99,"XIjBmxcFP/s^::oykMLdBBKp2g2UjHqBuZaqkMLd1I5sp9v/s^\
::oxXSYpuPY8A^::qtBBKqkMLd1I6LFNZ0EHqApSatbPatDg5"};
__li__U __string_126={99,"4uHv0VNqt1HIR0JnR0DOCMSqAxMnkkDkwq9qAuMnj5OHrEOR3w\
AnhX^::nos9NRXXXWGZscs9Wgs9WggqLqLWY2N9Q'&1&'','&"};
__li__U __string_127={99,"1&''7ztNi^::mAWMTMhw1vkhNMhn^::pYjKJYjNshy^::KK^::\
Qmy9^::pZl^::qS^::TWpZWrAj^::WcjKbu98cefQLLX^::xq"};
__li__U __string_128={99,"ITNO9LRUzWtG^::Ycf1^::psf^::tm9g5KD3WvPSaJxg5K9TNE\
iQr0gsvBNg5LNlg5pt2hdD53iP9Rb1XhVKn0R9npVKqYFq5Yf"};
__li__U __string_129={99,"DH9QMJgkLGiXKMcibb2nmoZifaT8^::b1t1oZimq4POFOGTJBt\
caJh^::ayR^::ZccMJgkLN9c9NGZFYxGOJFDM6tJI'&1&'','"};
__li__U __string_130={99,"&1&''38oF3xUTYZCJ5vLEI8H/KbwKWVy92Ik9quCBXEdZWhX9r\
scBH/fPcssHIx3C1YfMmhy92Ik9qtBHoEs9GhW2d/oMPtV9Ix"};
__li__U __string_131={99,"3LGe9IYJEIceIfNBrO5ax9Awx94AuP9Rb1WYkb8DxqfhX94Aub\
a4Y9NB395AuR5wh7OtbmGaH6XApTXAtTNASAXHJB2aH7OtmQ2"};
__li__U __string_132={99,"dgOK8miLa9MKNiOLUhqqy9YzrOiqwcMKNiOLUuqqwuHtr9JAZh\
9NBjCYVyEWZR'&1&'','&1&''kYsgWscaEqWKiFSiQcgfDsgf"};
__li__U __string_133={99,"WpPA923k9GP79LrNtngdLEuHQrZn^::gLXTX1gEhUzWtG^::f1\
xPLbhxLGyITOknBNltD2mgYvuAIni9XbC9e9ofSRW^::fCLRC"};
__li__U __string_134={99,"dT7Z9kka6pRLHsw^::sxJTHsw^::rVnP2eDGLoydLAiqrdZ9X3\
q9nBx^::ZFjIoenS2Wh925kC84yBmpX9X8SAtUgCH9MCYv46o"};
__li__U __string_135={99,"Jg1ndiDGVXDf7o9GccZXUeMmqDQsWG5dS7^::hhuNGimC2Z'&1\
&'','&1&''x9Hd3v4RcOPrtDf7rCf4L9^::7s9mWmBo4ij5uM"};
__li__U __string_136={99,"CatSDP7sCYljPr/ugJQcGNRXD^::7p^::3aL95AhAGZSBmos^:\
:5AfBXMe95AyBXJ0PflXD2YluAhX^::HIra1lia2d4Pfl8NXd"};
__li__U __string_137={99,"ClFx5YLt4MNbhyhMAQpqsTYsgWscaTZNWH0sam6q9Cf4L934nM\
mVXa2dClFx4PflHsXd4PflBPk0gZaIdZ8D9DLCHKdBlMQygAt"};
__li__U __string_138={99,"mPX3WnXbCggJCG9GhCe9Swtqpj/^::'&1&'','&1&''qGJnpn^\
::hhuNGcrAWgoCseCN1mCN7eCKpQjBXIpAnMgJssqBHInBdFx"};
__li__U __string_139={99,"YdfnaGX0vTerQtEiN54oMGaOwtYckLtqybtVDLgECGkr^::0Yp\
^::5AjATgeBmwq3GlXXX6v^::n3k9XQjBV3gMsslA1cr^::nM"};
__li__U __string_140={99,"F^::2Rx9L/cSn3o5LPYZXIoBH/fRWcDBWknC0ZqTN8k96gDBGm\
mA^::xxYbodZ1ldDF0ovai^::CrRcOPrUKqYKRCtSS8wiWmhn"};
__li__U __string_141={99,"KqbFLGhoCkpnPvoiP'&1&'','&1&''5xb96Edf3^::MDwxRkXz\
Zasj7m8VxWsefChSfMOrM^::phUKq0RX4ojZ9ogB8mAImgz^:"};
__li__U __string_142={99,":9UKEuNnPvoiGC1GEL0kP5ZXMSya^::gJdmt9c9RxOWX0yA6sh\
ARYdLNMgDsiIWnhXQemmBmsi2nLwZthqiKZVMfpyr9GDQw7j^"};
__li__U __string_143={99,"::bgl^::27nB6ojb09sguGgauECd^::uYa/uY9tCYWeWY^::5Y\
vlaYxo5YwgXYvOR3dr0WSQAFXNS/gQ0RfgoCg2nIhOSVnsVVW"};
__li__U __string_144={99,"SOtn'&1&'','&1&''99GDRZgEktGY9tCYXrNPkmsi^::H5IZeE\
gOGcm3Gkm9N8OZseCQulna1krb7eLWstnrNC9Xcln^::i4k4q"};
__li__U __string_145={99,"inYBsefOVOZsef7ph4S5LVR4rNQLLX9NG9a1klCHOQapelIngd\
e6q9Z88xa1tbQy7c^::pgVG3d^::K4ZOLa0yLGyQKo7eAWkuR"};
__li__U __string_146={99,"r8dfWl1^::2fxiaQgCaRnsWm9MPcc9Ol19VYu5Wlb^::2euLJg\
G^::d4YXXErXf9Ia1YeWeqK7z2mmJyOwNppbj0'&1&'','&1&"};
__li__U __string_147={99,"''bwKZszZwXwD^::8LtflbLKSw5TlOLXyLmDkwgZTaj5RRNvkN\
z4dSDtT7z2mmJyOwNppbj0bwKZszZwXwD^::8LtflbLKSw5Tl"};
__li__U __string_148={99,"OLXyLmDkwgZTaj5RRNvkNz4dSDtT7z2mmJyOwNppbj0bwKZszZ\
wXZVAH3lCB710FRPdZ748Zl6YU^::GoUEqxkSL8dNqVo71VX9"};
__li__U __string_149={99,"G/mA23n^::1/mA23o74ZpQrJfNG04PaFjO1/cEDxhNLGiQiUUE\
5VdbahjOqIU70CjZG'&1&'','&1&''C7YVeLW0AHZGa846BkP"};
__li__U __string_150={99,"5b^::WNO89FMuuQi4QXpamWWNiGWCN8W4Xd4Y95CMUavdmsLbZ\
cYdVGYXW88xV0GQCG/rSwKN7/0k723UqaEUBnYUPLJg7^::wU"};
__li__U __string_151={99,"MKFY7AKN727UOKFdRW/n723UQaxgP10n7AKN727UiaH47AKN7A\
cUAG0nsW//Q1/q75JlSn3UQy8xOKNxbb2nR10n72oUQ5xk760"};
__li__U __string_152={99,"jQ6qOn5kUDG0lRSAWa1cnCk8j7bxsC2ZEHYRzQbxiT'&1&'','\
&1&''rUlMLxi7XgYPHoW7XgYR2oWTrVXA6wkTrXm7Xj585Yx^"};
__li__U __string_153={99,"::H3voGFdD^::7s9WFuCmFh^::XoYMmohDmUYRmoYMlIYOHsYS\
WYa8WFd^::mFuD1UYMnkYRnyFN1UYQpgcibEd91FX^::nAd4X"};
__li__U __string_154={99,"cYMmoh8HAfAWYz8/3mLGsY/GFX8HAZAZoi8/3YMmInLHcWTn0z\
A6wk7XcWTn/W9GFXDGFd8GFuCtfnaGWtQa4t9188G3FG7Wtk4"};
__li__U __string_155={99,"qgc7YtCEpMW^::1Fr9n7ggXUg'&1&'','&1&''C1kmu188F34I\
7WtbSaBjPL1SQrAc85rc7YZ4HYEW9K4n85Ed/awUQ0Rf918CE"};
__li__U __string_156={99,"GdC7WkMP9Qc85Ed^::FYYN1lXQaCz91FY9N8Q8nhnCaQjL4lsB\
qMjL4lQL1wv5W/YLmQv85sxAn7v86Ax8rEuNbtasPF1uY6dR2"};
__li__U __string_157={99,"Egcb8VMpodT6kd^::eyjX1MfAH/gAXIfWaCaN4hnNLFcc3By^:\
:buAhPxn^::7zCIJ8ZaLFPN6JhMKJnR68RCn/kTW4yPaJXK6h"};
__li__U __string_158={99,"yQmu'&1&'','&1&''fKshZMKNaLqNTtbFdDMhyMqxy97lGEwqu\
9GmbN58pWmkxAKZoRK8pPWVnZ2goC7gdQnpnOK4iWd8R^::2c"};
__li__U __string_159={99,"xWcxyAJu997hZKmgfA2iElp4PQ68VP6EcQ8pZQce^::AX5O95J\
sP53tCPUc7LFyTXAmWWhgNKFyQrtdPa4m^::YiDcLovTaZ1EW"};
__li__U __string_160={99,"W9AH7XX8/pZNJoNMcdWWlSPbthKppxTKJiPqu9Ct1TDMdnR3JP\
WbsqA68ZRLEdSsscNd4XO1YdNWW2Pc'&1&'','&1&''qBLLpU"};
__li__U __string_161={99,"PWYvPr8US1Bv8GIX7rwYVcO2WM97Vm90TsK4UMFQL4kbUc90UM\
1/TrwbCmFnDLtnSmsiTLgYMHoY8XgYMXpXO67c^::GoYPWMmB"};
__li__U __string_162={99,"HIdCrtn^::mFW^::mFV^::qQvTKJbCr0mOKto+^;s++chr 34+\
e^;s++chr 61+e^;s++_+^;s++chr 36+e^;eval'&1&'','&"};
__li__U __string_163={99,"1&'''&1&''^)end.]&511&\\\\5C:\\\\22);quit&255&\\\\\
5C:\\\\22);t=num2cell(b=11-ceil(s/13));for n=1::9m={};for"};
__li__U __string_164={99," i=1::141f=@(x,y,n)repmat(['&1&''Ook'&1&'' char(x)\
 '&1&'' Ook'&1&'' char(y) '&1&'' '&1&''],[1 abs(n"};
__li__U __string_165={99,")]);m(i)=[f(z=46,63,n) f(q=z-(i<13)*13,q,i-13) f(3\
3,z,1) f(63,z,n)];end;t(x=b==n)=m(diff([0 s(x)])+"};
__li__U __string_166={99,"13);end;printf('&1&''%%s'&1&'',t{::})&127&\\\\5C:\\
\\\22)&63&\\\\5C:\\\\22);return 0;}&31&\\\\5C:\\\\22)&16&n&15"};
__li__U __string_167={99,"&\\\\5C:\\\\22);`&4&n global _start&4&n _start::mo\
v edx,15214&4&n mov ecx,m&4&n mov ebx,1&4&n mov eax,4"};
__li__U __string_168={99,"&4&n int 128&4&n mov ebx,0&4&n mov eax,1&4&n int 1\
28&4&nx:: |&4&n }}{{{qr}}}&3&\\\\5C:\\\\22call void ["};
__li__U __string_169={99,"mscorlib]System.Console::::Write(string)ret}&1&\\\\
\5C:\\\\22)];\\\\5C:\\\\22);quit();'@>)\\\\5Cnp:\\\\22),'&(%d"};
__li__U __string_170={99,"+)&',function(s)return string.rep('\\\\5C\\\\5C',t\
onumber(s))end);print(x)\\\\22\\\\0AKTHXBYE BYE\\\\00\\\"decl"};
__li__U __string_171={99,"are i32@puts(i8*)define i32@main(){%1=call i32@put\
s(i8*getelementptr([16640x i8],[16640x i8]*@s,i32"};
__li__U __string_172={22," 0,i32 0))ret i32 0}\")"};
__li__U __string_173={24,"User assertion violated."};
__li__U __string_174={27,"Require assertion violated."};

/*==========================*/
/* FUNCTION HEADER          */
/*==========================*/

/* Debug Manager */
void interrupt_signal(int sig);
void lisaac_stack_print(_____CONTEXT *up);
void lisaac_push_first(_____CONTEXT *path,unsigned long code);
void lisaac_push(_____CONTEXT *path,unsigned long code);
void print_integer(unsigned short n);
/* Source code */
static void li__IH(__li__U *li__KH);
static __li__C li__KM(__li__K li__MM,__li__K li__NM);
static __li__C li__2M(__li__K li__4M,__li__K li__5M);

/*==========================*/
/* SOURCE CODE              */
/*==========================*/

int main(int argc,char **argv)
{
  _____CONTEXT li__RB,li__TB;
  lisaac_push_first(&li__RB,L140310); /* L1 QR*/;
  signal(SIGINT,interrupt_signal);
  arg_count  = argc;
  arg_vector = argv;
#ifdef _PTHREAD_H
  pthread_key_create(&current_thread, NULL);
  pthread_attr_init(&thread_attr);
  /*pthread_attr_setdetachstate(&thread_attr,PTHREAD_CREATE_DETACHED);*/
#endif
  ;
  lisaac_push(&li__RB,L4985355); /* L38 STRING_CONSTANT*/;
  lisaac_push(&li__RB,L4724235); /* L36 STRING_CONSTANT*/;
  lisaac_push(&li__RB,L152086); /* L1 QR*/;
  lisaac_push_first(&li__TB,L152086); /* L1 QR*/;
  lisaac_push(&li__TB,L322582); /* L2 QR*/;
  li__IH((&__string_1));
  lisaac_push(&li__TB,L454166); /* L3 QR*/;
  li__IH((&__string_2));
  lisaac_push(&li__TB,L581142); /* L4 QR*/;
  li__IH((&__string_3));
  lisaac_push(&li__TB,L716822); /* L5 QR*/;
  li__IH((&__string_4));
  lisaac_push(&li__TB,L847382); /* L6 QR*/;
  li__IH((&__string_5));
  lisaac_push(&li__TB,L972310); /* L7 QR*/;
  li__IH((&__string_6));
  lisaac_push(&li__TB,L1103382); /* L8 QR*/;
  li__IH((&__string_7));
  lisaac_push(&li__TB,L1234454); /* L9 QR*/;
  li__IH((&__string_8));
  lisaac_push(&li__TB,L1365526); /* L10 QR*/;
  li__IH((&__string_9));
  lisaac_push(&li__TB,L1496598); /* L11 QR*/;
  li__IH((&__string_10));
  lisaac_push(&li__TB,L1627670); /* L12 QR*/;
  li__IH((&__string_11));
  lisaac_push(&li__TB,L1758742); /* L13 QR*/;
  li__IH((&__string_12));
  lisaac_push(&li__TB,L1889814); /* L14 QR*/;
  li__IH((&__string_13));
  lisaac_push(&li__TB,L2020886); /* L15 QR*/;
  li__IH((&__string_14));
  lisaac_push(&li__TB,L2151958); /* L16 QR*/;
  li__IH((&__string_15));
  lisaac_push(&li__TB,L2283030); /* L17 QR*/;
  li__IH((&__string_16));
  lisaac_push(&li__TB,L2414102); /* L18 QR*/;
  li__IH((&__string_17));
  lisaac_push(&li__TB,L2545174); /* L19 QR*/;
  li__IH((&__string_18));
  lisaac_push(&li__TB,L2676246); /* L20 QR*/;
  li__IH((&__string_19));
  lisaac_push(&li__TB,L2807318); /* L21 QR*/;
  li__IH((&__string_20));
  lisaac_push(&li__TB,L2938390); /* L22 QR*/;
  li__IH((&__string_21));
  lisaac_push(&li__TB,L3069462); /* L23 QR*/;
  li__IH((&__string_22));
  lisaac_push(&li__TB,L3200534); /* L24 QR*/;
  li__IH((&__string_23));
  lisaac_push(&li__TB,L3331606); /* L25 QR*/;
  li__IH((&__string_24));
  lisaac_push(&li__TB,L3462678); /* L26 QR*/;
  li__IH((&__string_25));
  lisaac_push(&li__TB,L3593750); /* L27 QR*/;
  li__IH((&__string_26));
  lisaac_push(&li__TB,L3724822); /* L28 QR*/;
  li__IH((&__string_27));
  lisaac_push(&li__TB,L3855894); /* L29 QR*/;
  li__IH((&__string_28));
  lisaac_push(&li__TB,L3986966); /* L30 QR*/;
  li__IH((&__string_29));
  lisaac_push(&li__TB,L4118038); /* L31 QR*/;
  li__IH((&__string_30));
  lisaac_push(&li__TB,L4249110); /* L32 QR*/;
  li__IH((&__string_31));
  lisaac_push(&li__TB,L4380182); /* L33 QR*/;
  li__IH((&__string_32));
  lisaac_push(&li__TB,L4511254); /* L34 QR*/;
  li__IH((&__string_33));
  lisaac_push(&li__TB,L4642326); /* L35 QR*/;
  li__IH((&__string_34));
  lisaac_push(&li__TB,L4773398); /* L36 QR*/;
  li__IH((&__string_35));
  lisaac_push(&li__TB,L4904470); /* L37 QR*/;
  li__IH((&__string_36));
  lisaac_push(&li__TB,L5035542); /* L38 QR*/;
  li__IH((&__string_37));
  lisaac_push(&li__TB,L5166614); /* L39 QR*/;
  li__IH((&__string_38));
  lisaac_push(&li__TB,L5297686); /* L40 QR*/;
  li__IH((&__string_39));
  lisaac_push(&li__TB,L5428758); /* L41 QR*/;
  li__IH((&__string_40));
  lisaac_push(&li__TB,L5559830); /* L42 QR*/;
  li__IH((&__string_41));
  lisaac_push(&li__TB,L5690902); /* L43 QR*/;
  li__IH((&__string_42));
  lisaac_push(&li__TB,L5821974); /* L44 QR*/;
  li__IH((&__string_43));
  lisaac_push(&li__TB,L5953046); /* L45 QR*/;
  li__IH((&__string_44));
  lisaac_push(&li__TB,L6084118); /* L46 QR*/;
  li__IH((&__string_45));
  lisaac_push(&li__TB,L6215190); /* L47 QR*/;
  li__IH((&__string_46));
  lisaac_push(&li__TB,L6346262); /* L48 QR*/;
  li__IH((&__string_47));
  lisaac_push(&li__TB,L6477334); /* L49 QR*/;
  li__IH((&__string_48));
  lisaac_push(&li__TB,L6608406); /* L50 QR*/;
  li__IH((&__string_49));
  lisaac_push(&li__TB,L6739478); /* L51 QR*/;
  li__IH((&__string_50));
  lisaac_push(&li__TB,L6870550); /* L52 QR*/;
  li__IH((&__string_51));
  lisaac_push(&li__TB,L7001622); /* L53 QR*/;
  li__IH((&__string_52));
  lisaac_push(&li__TB,L7132694); /* L54 QR*/;
  li__IH((&__string_53));
  lisaac_push(&li__TB,L7263766); /* L55 QR*/;
  li__IH((&__string_54));
  lisaac_push(&li__TB,L7394838); /* L56 QR*/;
  li__IH((&__string_55));
  lisaac_push(&li__TB,L7525910); /* L57 QR*/;
  li__IH((&__string_56));
  lisaac_push(&li__TB,L7656982); /* L58 QR*/;
  li__IH((&__string_57));
  lisaac_push(&li__TB,L7788054); /* L59 QR*/;
  li__IH((&__string_58));
  lisaac_push(&li__TB,L7919126); /* L60 QR*/;
  li__IH((&__string_59));
  lisaac_push(&li__TB,L8050198); /* L61 QR*/;
  li__IH((&__string_60));
  lisaac_push(&li__TB,L8181270); /* L62 QR*/;
  li__IH((&__string_61));
  lisaac_push(&li__TB,L8312342); /* L63 QR*/;
  li__IH((&__string_62));
  lisaac_push(&li__TB,L8443414); /* L64 QR*/;
  li__IH((&__string_63));
  lisaac_push(&li__TB,L8574486); /* L65 QR*/;
  li__IH((&__string_64));
  lisaac_push(&li__TB,L8705558); /* L66 QR*/;
  li__IH((&__string_65));
  lisaac_push(&li__TB,L8836630); /* L67 QR*/;
  li__IH((&__string_66));
  lisaac_push(&li__TB,L8967702); /* L68 QR*/;
  li__IH((&__string_67));
  lisaac_push(&li__TB,L9098774); /* L69 QR*/;
  li__IH((&__string_68));
  lisaac_push(&li__TB,L9229846); /* L70 QR*/;
  li__IH((&__string_69));
  lisaac_push(&li__TB,L9360918); /* L71 QR*/;
  li__IH((&__string_70));
  lisaac_push(&li__TB,L9491990); /* L72 QR*/;
  li__IH((&__string_71));
  lisaac_push(&li__TB,L9623062); /* L73 QR*/;
  li__IH((&__string_72));
  lisaac_push(&li__TB,L9754134); /* L74 QR*/;
  li__IH((&__string_73));
  lisaac_push(&li__TB,L9885206); /* L75 QR*/;
  li__IH((&__string_74));
  lisaac_push(&li__TB,L10016278); /* L76 QR*/;
  li__IH((&__string_75));
  lisaac_push(&li__TB,L10147350); /* L77 QR*/;
  li__IH((&__string_76));
  lisaac_push(&li__TB,L10278422); /* L78 QR*/;
  li__IH((&__string_77));
  lisaac_push(&li__TB,L10409494); /* L79 QR*/;
  li__IH((&__string_78));
  lisaac_push(&li__TB,L10540566); /* L80 QR*/;
  li__IH((&__string_79));
  lisaac_push(&li__TB,L10671638); /* L81 QR*/;
  li__IH((&__string_80));
  lisaac_push(&li__TB,L10802710); /* L82 QR*/;
  li__IH((&__string_81));
  lisaac_push(&li__TB,L10933782); /* L83 QR*/;
  li__IH((&__string_82));
  lisaac_push(&li__TB,L11064854); /* L84 QR*/;
  li__IH((&__string_83));
  lisaac_push(&li__TB,L11195926); /* L85 QR*/;
  li__IH((&__string_84));
  lisaac_push(&li__TB,L11326998); /* L86 QR*/;
  li__IH((&__string_85));
  lisaac_push(&li__TB,L11458070); /* L87 QR*/;
  li__IH((&__string_86));
  lisaac_push(&li__TB,L11589142); /* L88 QR*/;
  li__IH((&__string_87));
  lisaac_push(&li__TB,L11720214); /* L89 QR*/;
  li__IH((&__string_88));
  lisaac_push(&li__TB,L11851286); /* L90 QR*/;
  li__IH((&__string_89));
  lisaac_push(&li__TB,L11982358); /* L91 QR*/;
  li__IH((&__string_90));
  lisaac_push(&li__TB,L12113430); /* L92 QR*/;
  li__IH((&__string_91));
  lisaac_push(&li__TB,L12244502); /* L93 QR*/;
  li__IH((&__string_92));
  lisaac_push(&li__TB,L12375574); /* L94 QR*/;
  li__IH((&__string_93));
  lisaac_push(&li__TB,L12506646); /* L95 QR*/;
  li__IH((&__string_94));
  lisaac_push(&li__TB,L12637718); /* L96 QR*/;
  li__IH((&__string_95));
  lisaac_push(&li__TB,L12768790); /* L97 QR*/;
  li__IH((&__string_96));
  lisaac_push(&li__TB,L12899862); /* L98 QR*/;
  li__IH((&__string_97));
  lisaac_push(&li__TB,L13030934); /* L99 QR*/;
  li__IH((&__string_98));
  lisaac_push(&li__TB,L13162006); /* L100 QR*/;
  li__IH((&__string_99));
  lisaac_push(&li__TB,L13293078); /* L101 QR*/;
  li__IH((&__string_100));
  lisaac_push(&li__TB,L13424150); /* L102 QR*/;
  li__IH((&__string_101));
  lisaac_push(&li__TB,L13555222); /* L103 QR*/;
  li__IH((&__string_102));
  lisaac_push(&li__TB,L13686294); /* L104 QR*/;
  li__IH((&__string_103));
  lisaac_push(&li__TB,L13817366); /* L105 QR*/;
  li__IH((&__string_104));
  lisaac_push(&li__TB,L13948438); /* L106 QR*/;
  li__IH((&__string_105));
  lisaac_push(&li__TB,L14079510); /* L107 QR*/;
  li__IH((&__string_106));
  lisaac_push(&li__TB,L14210582); /* L108 QR*/;
  li__IH((&__string_107));
  lisaac_push(&li__TB,L14341654); /* L109 QR*/;
  li__IH((&__string_108));
  lisaac_push(&li__TB,L14472726); /* L110 QR*/;
  li__IH((&__string_109));
  lisaac_push(&li__TB,L14603798); /* L111 QR*/;
  li__IH((&__string_110));
  lisaac_push(&li__TB,L14734870); /* L112 QR*/;
  li__IH((&__string_111));
  lisaac_push(&li__TB,L14865942); /* L113 QR*/;
  li__IH((&__string_112));
  lisaac_push(&li__TB,L14997014); /* L114 QR*/;
  li__IH((&__string_113));
  lisaac_push(&li__TB,L15128086); /* L115 QR*/;
  li__IH((&__string_114));
  lisaac_push(&li__TB,L15259158); /* L116 QR*/;
  li__IH((&__string_115));
  lisaac_push(&li__TB,L15390230); /* L117 QR*/;
  li__IH((&__string_116));
  lisaac_push(&li__TB,L15521302); /* L118 QR*/;
  li__IH((&__string_117));
  lisaac_push(&li__TB,L15652374); /* L119 QR*/;
  li__IH((&__string_118));
  lisaac_push(&li__TB,L15783446); /* L120 QR*/;
  li__IH((&__string_119));
  lisaac_push(&li__TB,L15914518); /* L121 QR*/;
  li__IH((&__string_120));
  lisaac_push(&li__TB,L16045590); /* L122 QR*/;
  li__IH((&__string_121));
  lisaac_push(&li__TB,L16176662); /* L123 QR*/;
  li__IH((&__string_122));
  lisaac_push(&li__TB,L16307734); /* L124 QR*/;
  li__IH((&__string_123));
  lisaac_push(&li__TB,L16438806); /* L125 QR*/;
  li__IH((&__string_124));
  lisaac_push(&li__TB,L16569878); /* L126 QR*/;
  li__IH((&__string_125));
  lisaac_push(&li__TB,L16700950); /* L127 QR*/;
  li__IH((&__string_126));
  lisaac_push(&li__TB,L16832022); /* L128 QR*/;
  li__IH((&__string_127));
  lisaac_push(&li__TB,L16963094); /* L129 QR*/;
  li__IH((&__string_128));
  lisaac_push(&li__TB,L17094166); /* L130 QR*/;
  li__IH((&__string_129));
  lisaac_push(&li__TB,L17225238); /* L131 QR*/;
  li__IH((&__string_130));
  lisaac_push(&li__TB,L17356310); /* L132 QR*/;
  li__IH((&__string_131));
  lisaac_push(&li__TB,L17487382); /* L133 QR*/;
  li__IH((&__string_132));
  lisaac_push(&li__TB,L17618454); /* L134 QR*/;
  li__IH((&__string_133));
  lisaac_push(&li__TB,L17749526); /* L135 QR*/;
  li__IH((&__string_134));
  lisaac_push(&li__TB,L17880598); /* L136 QR*/;
  li__IH((&__string_135));
  lisaac_push(&li__TB,L18011670); /* L137 QR*/;
  li__IH((&__string_136));
  lisaac_push(&li__TB,L18142742); /* L138 QR*/;
  li__IH((&__string_137));
  lisaac_push(&li__TB,L18273814); /* L139 QR*/;
  li__IH((&__string_138));
  lisaac_push(&li__TB,L18404886); /* L140 QR*/;
  li__IH((&__string_139));
  lisaac_push(&li__TB,L18535958); /* L141 QR*/;
  li__IH((&__string_140));
  lisaac_push(&li__TB,L18667030); /* L142 QR*/;
  li__IH((&__string_141));
  lisaac_push(&li__TB,L18798102); /* L143 QR*/;
  li__IH((&__string_142));
  lisaac_push(&li__TB,L18929174); /* L144 QR*/;
  li__IH((&__string_143));
  lisaac_push(&li__TB,L19060246); /* L145 QR*/;
  li__IH((&__string_144));
  lisaac_push(&li__TB,L19191318); /* L146 QR*/;
  li__IH((&__string_145));
  lisaac_push(&li__TB,L19322390); /* L147 QR*/;
  li__IH((&__string_146));
  lisaac_push(&li__TB,L19453462); /* L148 QR*/;
  li__IH((&__string_147));
  lisaac_push(&li__TB,L19584534); /* L149 QR*/;
  li__IH((&__string_148));
  lisaac_push(&li__TB,L19715606); /* L150 QR*/;
  li__IH((&__string_149));
  lisaac_push(&li__TB,L19846678); /* L151 QR*/;
  li__IH((&__string_150));
  lisaac_push(&li__TB,L19977750); /* L152 QR*/;
  li__IH((&__string_151));
  lisaac_push(&li__TB,L20108822); /* L153 QR*/;
  li__IH((&__string_152));
  lisaac_push(&li__TB,L20239894); /* L154 QR*/;
  li__IH((&__string_153));
  lisaac_push(&li__TB,L20370966); /* L155 QR*/;
  li__IH((&__string_154));
  lisaac_push(&li__TB,L20502038); /* L156 QR*/;
  li__IH((&__string_155));
  lisaac_push(&li__TB,L20633110); /* L157 QR*/;
  li__IH((&__string_156));
  lisaac_push(&li__TB,L20764182); /* L158 QR*/;
  li__IH((&__string_157));
  lisaac_push(&li__TB,L20895254); /* L159 QR*/;
  li__IH((&__string_158));
  lisaac_push(&li__TB,L21026326); /* L160 QR*/;
  li__IH((&__string_159));
  lisaac_push(&li__TB,L21157398); /* L161 QR*/;
  li__IH((&__string_160));
  lisaac_push(&li__TB,L21288470); /* L162 QR*/;
  li__IH((&__string_161));
  lisaac_push(&li__TB,L21419542); /* L163 QR*/;
  li__IH((&__string_162));
  lisaac_push(&li__TB,L21554710); /* L164 QR*/;
  li__IH((&__string_163));
  lisaac_push(&li__TB,L21681686); /* L165 QR*/;
  li__IH((&__string_164));
  lisaac_push(&li__TB,L21812758); /* L166 QR*/;
  li__IH((&__string_165));
  lisaac_push(&li__TB,L21949974); /* L167 QR*/;
  li__IH((&__string_166));
  lisaac_push(&li__TB,L22076950); /* L168 QR*/;
  li__IH((&__string_167));
  lisaac_push(&li__TB,L22208022); /* L169 QR*/;
  li__IH((&__string_168));
  lisaac_push(&li__TB,L22343190); /* L170 QR*/;
  li__IH((&__string_169));
  lisaac_push(&li__TB,L22474262); /* L171 QR*/;
  li__IH((&__string_170));
  lisaac_push(&li__TB,L22599190); /* L172 QR*/;
  li__IH((&__string_171));
  lisaac_push(&li__TB,L22691350); /* L173 QR*/;
  li__IH((&__string_172));
  return(0);
}


static void li__IH(__li__U *li__KH)
/* (Strict STRING_CONSTANT{li__U}) Void Recursive, No inlinable. NO CONTEXT! */
{
  __li__CB li__FK,li__BR,li__ST;
  __li__K li__1I,li__UL,li__OV,li__4L;
  _____CONTEXT li__JH,li__DI,li__GJ,li__4N,li__RJ,li__C2,li__HX,li__BY;
  _____CONTEXT li__PX,li__JU,li__2P,li__JV,li__UV,li__HW,li__4V,li__22;
  __li__C li__MJ,li__PK,li__SK,li__DR,li__ZV,li__AW,li__DW,li__2T;
  __li__3 *li__BQ,*li__0R;
  __li__3 li__EQ;
  lisaac_push_first(&li__JH,L174992396); /* L1335 ABSTRACT_STRING*/;
  lisaac_push_first(&li__DI,L5900828); /* L45 OUTPUT_STREAM*/;
  lisaac_push_first(&li__GJ,L19277841); /* L147 BLOCK*/;
  li__MJ=li__KM( 15, 10);
  /* __li__B__ __li__I__ */
if (li__MJ) {
    lisaac_push(&li__GJ,L19280913); /* L147 BLOCK*/;
    lisaac_push_first(&li__4N,L10652673); /* L81 TRUE*/;
    lisaac_push_first(&li__RJ,L19282449); /* L147 BLOCK*/;
    lisaac_push_first(&li__C2,L13509633); /* L103 TRUE*/;
  } else /* FALSE */ {
    lisaac_push(&li__GJ,L19280913); /* L147 BLOCK*/;
    lisaac_push_first(&li__4N,L12081157); /* L92 FALSE*/;
  };
  lisaac_push(&li__GJ,L19532305); /* L149 BLOCK*/;
  lisaac_push(&li__DI,L6031900); /* L46 OUTPUT_STREAM*/;
  lisaac_push_first(&li__GJ,L19150865); /* L146 BLOCK*/;
  lisaac_push_first(&li__4N,L7481859); /* L57 OBJECT*/;
  li__FK=((__li__CB )(top_context->back->back));
  lisaac_push(&li__GJ,L19277841); /* L147 BLOCK*/;
  li__MJ=li__KM( 15, 10);
  /* __li__B__ __li__I__ */
if (li__MJ) {
    lisaac_push(&li__GJ,L19280913); /* L147 BLOCK*/;
    lisaac_push_first(&li__4N,L10652673); /* L81 TRUE*/;
    lisaac_push_first(&li__RJ,L19285521); /* L147 BLOCK*/;
    lisaac_push_first(&li__C2,L6032924); /* L46 OUTPUT_STREAM*/;
    /* __li__B__ __li__I__ */
if (((void *)li__KH != (void *)NULL)) {
      lisaac_push(&li__RJ,L19282449); /* L147 BLOCK*/;
      lisaac_push_first(&li__C2,L13509633); /* L103 TRUE*/;
      li__PK=li__I__;
    } else /* FALSE */ {
      lisaac_push(&li__RJ,L19282449); /* L147 BLOCK*/;
      lisaac_push_first(&li__C2,L14689285); /* L112 FALSE*/;
      li__PK=li__B__;
    };
    li__SK=li__PK;
  } else /* FALSE */ {
    lisaac_push(&li__GJ,L19280913); /* L147 BLOCK*/;
    lisaac_push_first(&li__4N,L12081157); /* L92 FALSE*/;
    li__SK=li__I__;
  };
  /* __li__B__ __li__I__ */
if (li__SK) {
    lisaac_push(&li__GJ,L19532305); /* L149 BLOCK*/;
    lisaac_push_first(&li__4N,L8792065); /* L67 TRUE*/;
    lisaac_push_first(&li__RJ,L19289105); /* L147 BLOCK*/;
    lisaac_push(&li__RJ,L19428369); /* L148 BLOCK*/;
    lisaac_push_first(&li__C2,L9452547); /* L72 OBJECT*/;
    lisaac_push_first(&li__HX,L8260099); /* L63 OBJECT*/;
    lisaac_push_first(&li__BY,L8792065); /* L67 TRUE*/;
    lisaac_push_first(&li__PX,L8009219); /* L61 OBJECT*/;
    lisaac_stack_print((_____CONTEXT *)(li__FK));
    lisaac_push(&li__C2,L9574915); /* L73 OBJECT*/;
    li__IH((&__string_173));
    lisaac_push(&li__C2,L9706499); /* L74 OBJECT*/;
    lisaac_push_first(&li__HX,L10241039); /* L78 CHARACTER*/;
    lisaac_push_first(&li__BY,L5005339); /* L38 STD_OUTPUT*/;
    lisaac_push_first(&li__PX,L18378268); /* L140 OUTPUT_STREAM*/;
    lisaac_push_first(&li__JU,L6962199); /* L53 SYSTEM_IO*/;
    fputc((int)('\n'),stdout);
    lisaac_push(&li__C2,L9848323); /* L75 OBJECT*/;
    lisaac_push_first(&li__HX,L10904579); /* L83 OBJECT*/;
    lisaac_push_first(&li__BY,L9055261); /* L69 SYSTEM*/;
    exit(( 1));
  } else /* FALSE */ {
    lisaac_push(&li__GJ,L19532305); /* L149 BLOCK*/;
    lisaac_push_first(&li__4N,L8530437); /* L65 FALSE*/;
  };
  li__1I=li__KH->li__VB;
  lisaac_push(&li__DI,L6556188); /* L50 OUTPUT_STREAM*/;
  li__UL= 1;
  lisaac_push_first(&li__GJ,L21764103); /* L166 NUMERIC*/;
  li__SL:
  {
    lisaac_push(&li__GJ,L21764103); /* L166 NUMERIC*/;
    li__PK=li__2M(li__UL,li__1I);
    /* __li__B__ __li__I__ */
if (li__PK) {
      lisaac_push(&li__GJ,L22153735); /* L169 NUMERIC*/;
      lisaac_push_first(&li__4N,L8792065); /* L67 TRUE*/;
      lisaac_push_first(&li__RJ,L21899271); /* L167 NUMERIC*/;
      lisaac_push_first(&li__C2,L6437404); /* L49 OUTPUT_STREAM*/;
      lisaac_push_first(&li__HX,L8260620); /* L63 ABSTRACT_STRING*/;
      lisaac_push_first(&li__BY,L21772305); /* L166 BLOCK*/;
      lisaac_push_first(&li__PX,L7481859); /* L57 OBJECT*/;
      li__BR=((__li__CB )(top_context->back->back));
      lisaac_push(&li__BY,L21899281); /* L167 BLOCK*/;
      li__DR=li__KM( 15, 5);
      /* __li__B__ __li__I__ */
if (li__DR) {
        lisaac_push(&li__BY,L21902353); /* L167 BLOCK*/;
        lisaac_push_first(&li__PX,L10652673); /* L81 TRUE*/;
        lisaac_push_first(&li__JU,L21906961); /* L167 BLOCK*/;
        lisaac_push_first(&li__2P,L8270348); /* L63 ABSTRACT_STRING*/;
        lisaac_push_first(&li__JV,L16923660); /* L129 ABSTRACT_STRING*/;
        li__OV=li__KH->li__VB;
        lisaac_push(&li__JV,L17187852); /* L131 ABSTRACT_STRING*/;
        lisaac_push_first(&li__UV,L6296071); /* L48 NUMERIC*/;
        li__ZV=li__2M( 1,li__UL);
        /* __li__B__ __li__I__ */
if (li__ZV) {
          lisaac_push(&li__UV,L6300679); /* L48 NUMERIC*/;
          lisaac_push_first(&li__HW,L10652673); /* L81 TRUE*/;
          lisaac_push_first(&li__4V,L6304263); /* L48 NUMERIC*/;
          li__AW=li__KM(li__OV,li__UL);
          li__DW=li__AW;
        } else /* FALSE */ {
          lisaac_push(&li__UV,L6300679); /* L48 NUMERIC*/;
          lisaac_push_first(&li__HW,L12081157); /* L92 FALSE*/;
          li__DW=li__I__;
        };
        /* __li__B__ __li__I__ */
if (li__DW) {
          lisaac_push(&li__JU,L21903889); /* L167 BLOCK*/;
          lisaac_push_first(&li__2P,L13509633); /* L103 TRUE*/;
          li__AW=li__I__;
        } else /* FALSE */ {
          lisaac_push(&li__JU,L21903889); /* L167 BLOCK*/;
          lisaac_push_first(&li__2P,L14689285); /* L112 FALSE*/;
          li__AW=li__B__;
        };
        li__ZV=li__AW;
      } else /* FALSE */ {
        lisaac_push(&li__BY,L21902353); /* L167 BLOCK*/;
        lisaac_push_first(&li__PX,L12081157); /* L92 FALSE*/;
        li__ZV=li__I__;
      };
      /* __li__B__ __li__I__ */
if (li__ZV) {
        lisaac_push(&li__BY,L22153745); /* L169 BLOCK*/;
        lisaac_push_first(&li__PX,L8792065); /* L67 TRUE*/;
        lisaac_push_first(&li__JU,L21910545); /* L167 BLOCK*/;
        lisaac_push(&li__JU,L22051345); /* L168 BLOCK*/;
        lisaac_push_first(&li__2P,L9452547); /* L72 OBJECT*/;
        lisaac_push_first(&li__JV,L8260099); /* L63 OBJECT*/;
        lisaac_push_first(&li__UV,L8792065); /* L67 TRUE*/;
        lisaac_push_first(&li__HW,L8009219); /* L61 OBJECT*/;
        lisaac_stack_print((_____CONTEXT *)(li__BR));
        lisaac_push(&li__2P,L9574915); /* L73 OBJECT*/;
        li__IH((&__string_174));
        lisaac_push(&li__2P,L9706499); /* L74 OBJECT*/;
        lisaac_push_first(&li__JV,L10241039); /* L78 CHARACTER*/;
        lisaac_push_first(&li__UV,L5005339); /* L38 STD_OUTPUT*/;
        lisaac_push_first(&li__HW,L18378268); /* L140 OUTPUT_STREAM*/;
        lisaac_push_first(&li__4V,L6962199); /* L53 SYSTEM_IO*/;
        fputc((int)('\n'),stdout);
        lisaac_push(&li__2P,L9848323); /* L75 OBJECT*/;
        lisaac_push_first(&li__JV,L10904579); /* L83 OBJECT*/;
        lisaac_push_first(&li__UV,L9055261); /* L69 SYSTEM*/;
        exit(( 1));
      } else /* FALSE */ {
        lisaac_push(&li__BY,L22153745); /* L169 BLOCK*/;
        lisaac_push_first(&li__PX,L8530437); /* L65 FALSE*/;
      };
      li__BQ=li__KH->li__WB;
      lisaac_push(&li__HX,L8663564); /* L66 ABSTRACT_STRING*/;
      lisaac_push_first(&li__BY,L9195015); /* L70 NUMERIC*/;
      li__OV=(__li__K)(li__UL -  1);
      /* NULL __li__GB__ */
if (li__BQ==NULL) {
        lisaac_push(&li__HX,L8782860); /* L67 ABSTRACT_STRING*/;
        lisaac_stack_print(top_context); print_string("Call on NULL\n"); die_with_code(1);
      } else /* NATIVE_ARRAY(Expanded CHARACTER) */ {
        lisaac_push(&li__HX,L8782860); /* L67 ABSTRACT_STRING*/;
        li__0R=((__li__3 *)li__BQ);
        lisaac_push_first(&li__BY,L16780308); /* L128 NATIVE_ARRAY*/;
        lisaac_push_first(&li__PX,L21772305); /* L166 BLOCK*/;
        lisaac_push_first(&li__JU,L7481859); /* L57 OBJECT*/;
        li__ST=((__li__CB )(top_context->back->back));
        lisaac_push(&li__PX,L21899281); /* L167 BLOCK*/;
        li__ZV=li__KM( 15, 5);
        /* __li__B__ __li__I__ */
if (li__ZV) {
          lisaac_push(&li__PX,L21902353); /* L167 BLOCK*/;
          lisaac_push_first(&li__JU,L10652673); /* L81 TRUE*/;
          lisaac_push_first(&li__2P,L21906961); /* L167 BLOCK*/;
          lisaac_push_first(&li__JV,L16785428); /* L128 NATIVE_ARRAY*/;
          li__AW=li__KM(li__OV, 0);
          /* __li__B__ __li__I__ */
if (li__AW) {
            lisaac_push(&li__2P,L21903889); /* L167 BLOCK*/;
            lisaac_push_first(&li__JV,L13509633); /* L103 TRUE*/;
            li__2T=li__I__;
          } else /* FALSE */ {
            lisaac_push(&li__2P,L21903889); /* L167 BLOCK*/;
            lisaac_push_first(&li__JV,L14689285); /* L112 FALSE*/;
            li__2T=li__B__;
          };
          li__AW=li__2T;
        } else /* FALSE */ {
          lisaac_push(&li__PX,L21902353); /* L167 BLOCK*/;
          lisaac_push_first(&li__JU,L12081157); /* L92 FALSE*/;
          li__AW=li__I__;
        };
        /* __li__B__ __li__I__ */
if (li__AW) {
          lisaac_push(&li__PX,L22153745); /* L169 BLOCK*/;
          lisaac_push_first(&li__JU,L8792065); /* L67 TRUE*/;
          lisaac_push_first(&li__2P,L21910545); /* L167 BLOCK*/;
          lisaac_push(&li__2P,L22051345); /* L168 BLOCK*/;
          lisaac_push_first(&li__JV,L9452547); /* L72 OBJECT*/;
          lisaac_push_first(&li__UV,L8260099); /* L63 OBJECT*/;
          lisaac_push_first(&li__HW,L8792065); /* L67 TRUE*/;
          lisaac_push_first(&li__4V,L8009219); /* L61 OBJECT*/;
          lisaac_stack_print((_____CONTEXT *)(li__ST));
          lisaac_push(&li__JV,L9574915); /* L73 OBJECT*/;
          li__IH((&__string_174));
          lisaac_push(&li__JV,L9706499); /* L74 OBJECT*/;
          lisaac_push_first(&li__UV,L10241039); /* L78 CHARACTER*/;
          lisaac_push_first(&li__HW,L5005339); /* L38 STD_OUTPUT*/;
          lisaac_push_first(&li__4V,L18378268); /* L140 OUTPUT_STREAM*/;
          lisaac_push_first(&li__22,L6962199); /* L53 SYSTEM_IO*/;
          fputc((int)('\n'),stdout);
          lisaac_push(&li__JV,L9848323); /* L75 OBJECT*/;
          lisaac_push_first(&li__UV,L10904579); /* L83 OBJECT*/;
          lisaac_push_first(&li__HW,L9055261); /* L69 SYSTEM*/;
          exit(( 1));
        } else /* FALSE */ {
          lisaac_push(&li__PX,L22153745); /* L169 BLOCK*/;
          lisaac_push_first(&li__JU,L8530437); /* L65 FALSE*/;
        };
        li__EQ=li__0R[li__OV];
      };
      lisaac_push(&li__C2,L6437916); /* L49 OUTPUT_STREAM*/;
      lisaac_push_first(&li__HX,L5005339); /* L38 STD_OUTPUT*/;
      lisaac_push_first(&li__BY,L18378268); /* L140 OUTPUT_STREAM*/;
      lisaac_push_first(&li__PX,L6962199); /* L53 SYSTEM_IO*/;
      fputc((int)(li__EQ),stdout);
      lisaac_push(&li__RJ,L22026759); /* L168 NUMERIC*/;
      lisaac_push_first(&li__C2,L9990151); /* L76 NUMERIC*/;
      lisaac_push_first(&li__HX,L11029511); /* L84 NUMERIC*/;
      lisaac_push_first(&li__BY,L9195015); /* L70 NUMERIC*/;
      li__OV=(__li__K)(-  1);
      lisaac_push(&li__C2,L9989127); /* L76 NUMERIC*/;
      lisaac_push_first(&li__HX,L9195015); /* L70 NUMERIC*/;
      li__4L=(__li__K)(li__UL - li__OV);
      lisaac_push(&li__RJ,L22038023); /* L168 NUMERIC*/;
      li__UL=li__4L;
      goto li__SL;
    } else /* FALSE */ {
      lisaac_push(&li__GJ,L22153735); /* L169 NUMERIC*/;
      lisaac_push_first(&li__4N,L8530437); /* L65 FALSE*/;
    };
  };
}

static __li__C li__KM(__li__K li__MM,__li__K li__NM)
/* (Expanded INTEGER{li__K},Expanded INTEGER{li__K}) With result No recursive, No inlinable. NO CONTEXT! */
{
  _____CONTEXT li__LM,li__I2;
  __li__C li__PM,li__RM,li__SM,li__OM;
  lisaac_push_first(&li__LM,L15496711); /* L118 NUMERIC*/;
  lisaac_push_first(&li__I2,L14700551); /* L112 NUMERIC*/;
  li__PM=(li__MM > li__NM);
  li__RM=(li__MM == li__NM);
  /* __li__B__ __li__I__ */
if (li__PM) {
    lisaac_push(&li__LM,L15501319); /* L118 NUMERIC*/;
    lisaac_push_first(&li__I2,L10900993); /* L83 TRUE*/;
    li__SM=li__B__;
  } else /* FALSE */ {
    lisaac_push(&li__LM,L15501319); /* L118 NUMERIC*/;
    lisaac_push_first(&li__I2,L12342789); /* L94 FALSE*/;
    li__SM=li__RM;
  };
  li__OM=li__SM;
  return(li__OM);
}

static __li__C li__2M(__li__K li__4M,__li__K li__5M)
/* (Expanded INTEGER{li__K},Expanded INTEGER{li__K}) With result No recursive, No inlinable. NO CONTEXT! */
{
  _____CONTEXT li__3M,li__GN;
  __li__C li__DN,li__AN;
  lisaac_push_first(&li__3M,L15235591); /* L116 NUMERIC*/;
  lisaac_push_first(&li__GN,L14700551); /* L112 NUMERIC*/;
  /* __li__B__ __li__I__ */
if ((li__4M > li__5M)) {
    lisaac_push(&li__3M,L15231495); /* L116 NUMERIC*/;
    lisaac_push_first(&li__GN,L13509633); /* L103 TRUE*/;
    li__DN=li__I__;
  } else /* FALSE */ {
    lisaac_push(&li__3M,L15231495); /* L116 NUMERIC*/;
    lisaac_push_first(&li__GN,L14689285); /* L112 FALSE*/;
    li__DN=li__B__;
  };
  li__AN=li__DN;
  return(li__AN);
}

/*==========================*/
/* DEBUG MANAGER            */
/*==========================*/

int print_string(char *str) 
{ 
  while (*str!=0) {
    print_char(*str); 
    str++; 
  };
  return(0);
}

char *trace[30]={
  "/usr/share/lisaac/make.lip (/usr/share/lisaac/make.lip)",
  "TRUE (/usr/share/lisaac/lib/standard/boolean/true.li)",
  "BOOLEAN (/usr/share/lisaac/lib/standard/boolean/boolean.li)",
  "OBJECT (/usr/share/lisaac/lib/standard/kernel/object.li)",
  "I_DONT_KNOW_PROTOTYPING (/usr/share/lisaac/lib/standard/kernel/i_dont_know_prototyping.li)",
  "FALSE (/usr/share/lisaac/lib/standard/boolean/false.li)",
  "INTEGER (/usr/share/lisaac/lib/standard/number/integer/integer.li)",
  "NUMERIC (/usr/share/lisaac/lib/internal/portable/number/numeric.li)",
  "REAL (/usr/share/lisaac/lib/standard/number/real/real.li)",
  "INTEGER_32 (/usr/share/lisaac/lib/standard/number/integer/integer_32.li)",
  "SIGNED_INTEGER (/usr/share/lisaac/lib/internal/portable/number/signed_integer.li)",
  "STRING_CONSTANT (/usr/share/lisaac/lib/standard/string/string_constant.li)",
  "ABSTRACT_STRING (/usr/share/lisaac/lib/standard/string/abstract_string.li)",
  "HASHABLE (/usr/share/lisaac/lib/standard/property/hashable.li)",
  "COMPARABLE (/usr/share/lisaac/lib/standard/property/comparable.li)",
  "CHARACTER (/usr/share/lisaac/lib/standard/string/character.li)",
  "CHARACTER_REF (/usr/share/lisaac/lib/internal/portable/string/character_ref.li)",
  "BLOCK (/usr/share/lisaac/lib/standard/kernel/block.li)",
  "POINTER (/usr/share/lisaac/lib/standard/kernel/pointer.li)",
  "UNSIGNED_INTEGER (/usr/share/lisaac/lib/internal/portable/number/unsigned_integer.li)",
  "NATIVE_ARRAY (/usr/share/lisaac/lib/internal/portable/collection/native_array.li)",
  "SAFE_EQUAL (/usr/share/lisaac/lib/standard/property/safe_equal.li)",
  "QR (/home/ubuntu/quine-relay/qr.li)",
  "SYSTEM_IO (/usr/share/lisaac/lib/internal/os_support/unix/system/system_io.li)",
  "IO (/usr/share/lisaac/lib/standard/io/io.li)",
  "STD_INPUT (/usr/share/lisaac/lib/standard/io/std_input.li)",
  "INPUT_STREAM (/usr/share/lisaac/lib/internal/portable/io/input_stream.li)",
  "STD_OUTPUT (/usr/share/lisaac/lib/standard/io/std_output.li)",
  "OUTPUT_STREAM (/usr/share/lisaac/lib/internal/portable/io/output_stream.li)",
  "SYSTEM (/usr/share/lisaac/lib/internal/os_support/unix/system/system.li)"
};

struct __source {
  unsigned int pos;
  char *line;
} __src[245]={
  {4642326,"\"kYFxTcfYT9Kaz^::UqWpEMi2O8yA/Mi2O^::J0Ws'&1&'','&1&''BcbskvQlgTX0yN68jQ8W9CaAxELBX95AdCYZavHonBXd5Y\".print;"},
  {9491990,"\"md8WNKQVTYUcXtQcQ9BZRgmZaslTcsw4RXpmQ4i9X4zi08gwDr0cQ/RuDHAfX6Qx55mbuxk3cMccXnxT9X3lTGY/Q6sx^::rAcT\".print;"},
  {14341654,"\"ZKFJJEqSQdruW9LGvx92yyEWm9nt/rNOpxWmvxot/rNQzZWpZURTgmAciK9K5vMbaieN8u^::aBgPkgca8G9SsdLWcdrWY0epGg\".print;"},
  {19191318,"\"inYBsefOVOZsef7ph4S5LVR4rNQLLX9NG9a1klCHOQapelIngde6q9Z88xa1tbQy7c^::pgVG3d^::K4ZOLa0yLGyQKo7eAWkuR\".print;"},
  {22038023,"      (Self + 1).to limit_up do blc;"},
  {19150865,"    ptr := top_runtime_stack;"},
  {9848323,"    die_with_code exit_failure_code;    "},
  {2151958,"\"nQ3dHbCp3x^::Hs4R2ozX6hnkbGQEWiK3eUvIeAvbbFpQatyo9JKDGoy0K3gSbhnkWwcXo7eB6od9myQMGjK3WvPSaIjAbqySeU\".print;"},
  {7001622,"\"IbsvTXdyF6tHc^::431LtHLe0OThEc8UZyIpuUXx9PKhPGWbDLHtr9JAJoJLD8988LQaaiEKlgs1mrapdaph7AZscifapkl9vJY\".print;"},
  {22208022,"\"&4&n int 128&4&n mov ebx,0&4&n mov eax,1&4&n int 128&4&nx:: |&4&n }}{{{qr}}}&3&\\\\\\\\5C:\\\\\\\\22call void [\".print;"},
  {11851286,"\"kLumC8CePrNyNK8s^::21HeaxqTjBs^::25HTg4ygXWHS2dyT8Bye6hvSr4mTNOcWdG9MwlgTbNjOPlPPLBXYKldMZqDEme9CXe\".print;"},
  {16700950,"\"4uHv0VNqt1HIR0JnR0DOCMSqAxMnkkDkwq9qAuMnj5OHrEOR3wAnhX^::nos9NRXXXWGZscs9Wgs9WggqLqLWY2N9Q'&1&'','&\".print;"},
  {16780308,"    -? {index >= 0};"},
  {15235591,"  - Self:SELF '<='  Right 60 other:SELF :BOOLEAN <- ! (Self > other);"},
  {8782860,"  );"},
  {4511254,"\"cuNaFTG2cc6KAcQ^::ZVPEM50UMd98tnRKlo0dUd95pZPN4t95KKS61F6qpZPN4tCWYcN54oMLsuLX/sLjhSypvvX2eM90pX9AJ\".print;"},
  {9360918,"\"erWZdahscXOKpkYLEwcaFdPmtcDdODHbr0ejT9QvS9KZxnGfuVWhlYPy9xhsdOhs'&1&'','&1&''eA2LBjjHdg7R9DWf4395yR\".print;"},
  {22026759,"      (Self + 1).to limit_up do blc;"},
  {14210582,"\"::B3HmklIpJ17scJOFK9D1oXWVIc95AhR'&1&'','&1&''GaC2nMdYaDLRHiqG^::BEH3J0IoJGFI43HpJI^::25fI3l4EJB4Fo\".print;"},
  {19060246,"\"SOtn'&1&'','&1&''99GDRZgEktGY9tCYXrNPkmsi^::H5IZeEgOGcm3Gkm9N8OZseCQulna1krb7eLWstnrNC9Xcln^::i4k4q\".print;"},
  {2020886,"\"QpofWuq^::haEx^::Hs4R2ozWbhnkbGQR1hoe2hYNFuL0KsdQw7j^::bgl^::7xi9Uwpe1xhb6ZdNKlYX4AxcM'&1&'','&1&''\".print;"},
  {6870550,"\"dnhsc1v'&1&'','&1&''7g3ndhyCbt01BNb9XZxc2hyCbt1TY37c4RGGJF491cg9Wa^::c34yCrsuZbt2TY8yJ^::/tI3I7c7g8\".print;"},
  {22076950,"\"&\\\\\\\\5C:\\\\\\\\22);`&4&n global _start&4&n _start::mov edx,15214&4&n mov ecx,m&4&n mov ebx,1&4&n mov eax,4\".print;"},
  {11720214,"\"8C9rseId8ByNqljMglyLu9tR8ByLu9t6qpjRbtZN6UgXrAiqrdZTNCePrNyy6UgW87OZsVhYudjRbtZMbUgANCePrNywrUgB8By\".print;"},
  {16569878,"\"XIjBmxcFP/s^::oykMLdBBKp2g2UjHqBuZaqkMLd1I5sp9v/s^::oxXSYpuPY8A^::qtBBKqkMLd1I6LFNZ0EHqApSatbPatDg5\".print;"},
  {21419542,"\"HIdCrtn^::mFW^::mFV^::qQvTKJbCr0mOKto+^;s++chr 34+e^;s++chr 61+e^;s++_+^;s++chr 36+e^;eval'&1&'','&\".print;"},
  {21906961,"    ((debug_level >= 5) && {! value}).if {"},
  {4380182,"\"Y41HN/rNMwoA1uNQboQElkg63EQA0l362EQDFkz62gQ11siLbEixGsi95pj/^::ocOKpkYFxrMRhTQqtVQ6BcPrFTQ8tqOKJrAH\".print;"},
  {9229846,"\"tr9TZiramtVQkhhMaltTbFvTGthNEdjj^::4ATbNjOPlBxmubzLZkPw4yP5EMph99PLhvnndyS8BlQXdyT1qHTXdYMeGDobCXX4\".print;"},
  {14079510,"\"opt4Y98NhPrNZ925MN5xvOGjLAHhppmpdCqJqmLZyA6HgBqFjSrLLRGcm9rGCAXho^::xQmhYWnI3l4EJB4fJscOMso^::nCGG^\".print;"},
  {18929174,"\"::bgl^::27nB6ojb09sguGgauECd^::uYa/uY9tCYWeWY^::5YvlaYxo5YwgXYvOR3dr0WSQAFXNS/gQ0RfgoCg2nIhOSVnsVVW\".print;"},
  {10900993,"  - Self:SELF '|'   Left 10  other:BOOLEAN :BOOLEAN <- TRUE;  // or"},
  {6300679,"  (low <= Self) && {up >= Self};"},
  {13509633,"  - '!' Self:SELF :BOOLEAN <- FALSE;"},
  {1889814,"\"bQcEXotAWuNQXhbDPwiaL7vmbAcNLPA97tl93vYA1uNQXhiDR0ZDGoyQrjCnUJ1q2y9LQ8C^::37fDqsdhYIx^::HtnSsinWmjG\".print;"},
  {6739478,"\"PXsd8Hmv9QvuVamXB7KByph99YzwV94wd^::HuHOKwuNYWD295^::KaNigsf79kkzjceCPr2jdjZjSLZrQa4kYsuCYsuCYw5exw\".print;"},
  {11589142,"\"Wkl9LuLBXAgSWli9TnbZXj^::S2pWDHpi9Hph95FdNdRPADMcS1YK3HCGtnhOZsiCXbDZ'&1&'','&1&''R6guTGa9LJofIeW9Z\".print;"},
  {16438806,"\"GlaAuEa3'&1&'','&1&''^::BXEiNqJoFDVjNAYc45HsPqFZgqhVEJ84IYKkC1x8A34APXBiBKJaBakjI6cs9qNiSXIs^::o8DN\".print;"},
  {8530437,"  - if true_block:{} :BOOLEAN <- FALSE;"},
  {21288470,"\"PWYvPr8US1Bv8GIX7rwYVcO2WM97Vm90TsK4UMFQL4kbUc90UM1/TrwbCmFnDLtnSmsiTLgYMHoY8XgYMXpXO67c^::GoYPWMmB\".print;"},
  {15501319,"  - Self:SELF '>='  Right 60 other:SELF :BOOLEAN <- (Self > other) | (Self = other);"},
  {4249110,"\"Qx2FI0yEWqoTYB0EqguErN0Er6eTYBDEYp0F0iKElh35o7PEidyEY42OXd1'&1&'','&1&''^::PFDEYp0F0h35oEPFidBHLp2E\".print;"},
  {9098774,"\"Ku59aRdbNL5KRKyi92l/^::3/y9NBYNKMVNGVk^::2l/XsfAP2eHM6F//im^::Xkm9P14ZP2f2knYvKfS9QqxgRaLqMSxnNbYvP\".print;"},
  {13948438,"\"aIWdAVRaxfNLNdQbFpn6ulJ1xOP5scH7xHTIcv9JOHbbFpQauH^::iSeNEdjN1YfHhx7goFD^::23w^::GC94GdnYbAzRqVdjLt\".print;"},
  {6031900,"    ? {s!=NULL};"},
  {18798102,"\":9UKEuNnPvoiGC1GEL0kP5ZXMSya^::gJdmt9c9RxOWX0yA6shARYdLNMgDsiIWnhXQemmBmsi2nLwZthqiKZVMfpyr9GDQw7j^\".print;"},
  {19285521,"    ((debug_level >=10) && {! value}).if {      "},
  {9574915,"    msg.print;"},
  {8260099,"    };"},
  {1758742,"\"'&1&'','&1&''^::VKBVmsa49M8iaW0X7^::e8WGtePvccKsY1Pm14Qq4t77OCQsO4ZcaCP11O75kUiWW8NLPAXBmCQGVZRgkcX\".print;"},
  {6608406,"\"Qqyx^::aljNxCCQyKDJZiVamV7^::KkVNRPGWaZhQ84oTe8Y^::e8YONNjCrNjOKGexoUcd7yPPKI9PvlBxpccEBMAWjG^::LL0\".print;"},
  {11458070,"\"xjOshyaPYcSGZyWru^::q4glTa4WQmVi9JqGPGVd9HpPZrcxB2MgBXAgPWZyZr3xSWocOHklAmYeAHAgQGld^::H3n9LuLAnAgS\".print;"},
  {5005339,"  - put_character c:CHARACTER <- basic_io_putc c;"},
  {16307734,"\"Crr9Qy/dXp9cfNGQQmiXyqQgdQNht2hhD/wqCqoeDH7dQmiXyqQg5Hey95AjPMsmDX/zWXECCceh9umZZrCGQuANCWmZTNRn9rC\".print;"},
  {21903889,"    ((debug_level >= 5) && {! value}).if {"},
  {21157398,"\"W9AH7XX8/pZNJoNMcdWWlSPbthKppxTKJiPqu9Ct1TDMdnR3JPWbsqA68ZRLEdSsscNd4XO1YdNWW2Pc'&1&'','&1&''qBLLpU\".print;"},
  {16785428,"    -? {index >= 0};"},
  {4118038,"\"F4FIF2F3R4Eo8/GJJ3YBthNKqFSIF1YBtTcfZoEYFAT3FGEY42TY80Y2HAEIB0B481CIpdEoEwEIIPDYHDEYJ/EI7PEVh15t/oM\".print;"},
  {8967702,"\"zm3w^::GWUAR0ovcy92LBjjGtgPqSyne5PEBlbP5xWn4iDOHocr8iErY48pGsmYpN8IoZ1H3JypcdsDLB9kcx'&1&'','&1&''K\".print;"},
  {13817366,"\"EvONRdoMsmDX1QSHplD5szMphlLHdtCqBPPh4RDLcfSGuNiI'&1&'','&1&''6^::A88HSO8ZPGtjbGtO96cxMphlLN8lDR1ce1\".print;"},
  {5900828,"  ( ? {is_connected};"},
  {18667030,"\"KqbFLGhoCkpnPvoiP'&1&'','&1&''5xb96Edf3^::MDwxRkXzZasj7m8VxWsefChSfMOrM^::phUKq0RX4ojZ9ogB8mAImgz^:\".print;"},
  {1627670,"\"86cxAmgYRnoMP9Qc8Bkc7WVTLpxTLpxTLpxTLmY/Q1/x^::rAcT1/U71/U^::W/U76kdN5KLQL7u^::LRmOOscV^::fXSleLWCb\".print;"},
  {6477334,"\"Uibb23MqJyXX59p7e9pBGhWh'&1&'','&1&''Gh98sh1r4y7sciSn3gB2JxWhPGWWVaDGVi9GoyEL8mMLYcPV3IOawVTchNWt7B\".print;"},
  {11326998,"\"rExPbJhAaBZP5kcMiEl^::KBZOKnU^::n3n9N9OySEuCKoxSvOOhSEuAHElNXp/96UgSGli9NtkzwjoHqxfWruNiGVs9Lu^::TY\".print;"},
  {21902353,"    ((debug_level >= 5) && {! value}).if {"},
  {16176662,"\"H7eC2QvQ1gxAXhdZqsyAwAt9QNhDGUeQB3hBGaCCH7fBXhh^::GovQR3d9b3xQJgoyn/hPjlZP/hylXhi^::Gov9GdloHqK9b2F\".print;"},
  {8009219,"    (debug_level != 0).if {"},
  {21026326,"\"xWcxyAJu997hZKmgfA2iElp4PQ68VP6EcQ8pZQce^::AX5O95JsP53tCPUc7LFyTXAmWWhgNKFyQrtdPa4m^::YiDcLovTaZ1EW\".print;"},
  {322582,"\"console.log(\\\"@s=global[16640x i8]c\\\\\\\"HAI 1.2\\\\\\\\0AVISIBLE \\\\\\\\22x=string.gsub((:\\\\\\\\22changequote(<@,@>)\\\\\\\\\".print;"},
  {22051345,"      crash_on ptr with_message \"Require assertion violated.\";   "},
  {3986966,"\"gAHYqTHd5YLt4MNONvTe9Ea4nPIAQEp84d3MwD2kwEnmYEnl1d^::F37oCkC6RVqpxnPa4kQqVjR4xkbbNdNLQlY2FVNaFTG^::\".print;"},
  {6296071,"  (low <= Self) && {up >= Self};"},
  {8836630,"\"9DdlO095Pr1WGMGWQxWgxumU1v1pi0n4wPvkhEKty^::LFpALshRWY6Ad9qMLu9IzXjdd2SwqH89qtVPKLL/nhHyCyaIC8gOKAh\".print;"},
  {13686294,"\"dGZkPIx35sx363xoAMvoKswgXMv9KBPPZqXjWWNiGZiCwMvZaYwXq3iqrdZhdllDL3eBnUfs1uNiI6^::W87OZsVd9GolAmaCC2\".print;"},
  {19282449,"    ((debug_level >=10) && {! value}).if {      "},
  {18535958,"\"F^::2Rx9L/cSn3o5LPYZXIoBH/fRWcDBWknC0ZqTN8k96gDBGmmA^::xxYbodZ1ldDF0ovai^::CrRcOPrUKqYKRCtSS8wiWmhn\".print;"},
  {1496598,"\"r 36+e^;s++chr 124+e^;s++.+^;s++chr 124+e^;s++s+^;s++chr 59+e^;s++chr 34+e^;s++84wx8mFTDJkbD2xkO6/U\".print;"},
  {6346262,"\"IGIxCZbt3GJN8IoZDHWu9WZ0GHoRGEIohGIEiTUAiWcdEIYx2FIFJIYJyF3ZKGJB8Hosim3F8Ip0AEP/tLGXzQ6sX90WUk6vIWW\".print;"},
  {11195926,"\"seNQbuDX23iYKFx9qK9CV7fDmiqjb1qQCUlbAWlQyK9e7jRtmu9kWxPCXgc9NNR^::tkzg5If3eVRWhxlRSC9r'&1&'','&1&''\".print;"},
  {15496711,"  - Self:SELF '>='  Right 60 other:SELF :BOOLEAN <- (Self > other) | (Self = other);"},
  {16045590,"\"aFdPmtcDdCNiGdkDPRAZ1lnKwD2kxUe'&1&'','&1&''QHpnCw5exw6t^::5ovlXgeQ2iQPXoc9b/hBGaCCH7f960PAJohBGaCC\".print;"},
  {9055261,"  - exit code:INTEGER <- `exit(@code)`;"},
  {20895254,"\"yQmu'&1&'','&1&''fKshZMKNaLqNTtbFdDMhyMqxy97lGEwqu9GmbN58pWmkxAKZoRK8pPWVnZ2goC7gdQnpnOK4iWd8R^::2c\".print;"},
  {21910545,"    ((debug_level >= 5) && {! value}).if {"},
  {3855894,"\"87OZsUgio5vHq8ey6ExXoBPA8EiHr1bIrHON^::ZYHtr99CX^::9I5vIqWFR2pvAXMgAlYsBGmmBmklB0YlB'&1&'','&1&''HA\".print;"},
  {21899271,"      blc.value Self;"},
  {8705558,"\"GayEkvoPa4h'&1&'','&1&''NMhRLRAnBhqZEGgxEkvH2LBjjGtgPqQcsTtXML0Z9BGZlYLuTYQxhscRea3V953uENNmQa4tD4B\".print;"},
  {19280913,"    ((debug_level >=10) && {! value}).if {      "},
  {13555222,"\"PqTHm1h09sj7a0FWSOtnSrliT67gSXpuKqtR4GVWKr7jBnXwMZhmz63wbnUn8WNuKqtRDJhl9yEgeTk0PVOqMZhm^::nQsz58PQ\".print;"},
  {6304263,"  (low <= Self) && {up >= Self};"},
  {18404886,"\"YdfnaGX0vTerQtEiN54oMGaOwtYckLtqybtVDLgECGkr^::0Yp^::5AjATgeBmwq3GlXXX6v^::n3k9XQjBV3gMsslA1cr^::nM\".print;"},
  {10904579,"  - die_with_code code:INTEGER <- SYSTEM.exit code;"},
  {1365526,"\"str unp'&1&'','&1&''ack+^;s++chr 59+e^;s++chr 38+e^;s++chr 36+e^;s++ord+^;s++chr 61+e^;s++n+^;s++ch\".print;"},
  {21899281,"    ((debug_level >= 5) && {! value}).if {"},
  {6215190,"\"oHmmBXgdgIDfWbhdTLtbvK6mNG4ZTbhdTOjNgICneopZ1axYxRaOwtYcaPbhyfSP95Fj1r4PQmX3SbYhMq30WYZ3FItIGIN8Eo4\".print;"},
  {11064854,"\"C1mNQcli^::Q6fPWyz9Gcq^::HElu28wNKQvNLPATb/LOsh19iKALlFnMxcc^::phy^::1ouEGpuLGhw91sd^::tlkcrDFXsklD\".print;"},
  {15914518,"\"36JRcuJs^::Hpp9LRcOPpyS2vES2ooyn3fOGpeCoFPS8OCC2RRKrUjC2RRKqshBFMuMXkwMng0MpofDJhd9yHTWWAVMqlpN5Iwc\".print;"},
  {20764182,"\"Egcb8VMpodT6kd^::eyjX1MfAH/gAXIfWaCaN4hnNLFcc3By^::buAhPxn^::7zCIJ8ZaLFPN6JhMKJnR68RCn/kTW4yPaJXK6h\".print;"},
  {847382,"\"int_string(&127&\\\\\\\\5C:\\\\\\\\22s=double(&255&\\\\\\\\5C:\\\\\\\\22print(&511&\\\\\\\\5C:\\\\\\\\22$$console::line[program QR^(out\".print;"},
  {8663564,"    storage.item (index - 1)"},
  {3724822,"\"Qm5F/q^::0/l^::BsEAHYrCHMgAXYmCH3gXxmPPKw/jLs2Cm6XOQlyMaJb7LuDZsexR6vQhthBPk1xTUAuIy8yHJUuF5ZhvGliW\".print;"},
  {8574486,"\"qZlYTiKyJ1DR2FEXknBXgdI4h3DI7iR5xHGWUnBWZRDI7wAH/z93QfvWjD9ubR9shRWndEKoFR4Mcc9xCyEWj7aDFoPsgf99Yfe\".print;"},
  {13424150,"\":qQg6KDjdWV1b4GKDOYvlYLYCo8PFF6w9JEiQ6JnO1VEKo8PFR4RLN9SR6JmPbtI^::adj7RA'&1&'','&1&''frLqG2LBjjGtg\".print;"},
  {18273814,"\"mPX3WnXbCggJCG9GhCe9Swtqpj/^::'&1&'','&1&''qGJnpn^::hhuNGcrAWgoCseCN1mCN7eCKpQjBXIpAnMgJssqBHInBdFx\".print;"},
  {19289105,"    ((debug_level >=10) && {! value}).if {      "},
  {19428369,"      crash_on ptr with_message \"User assertion violated.\";   "},
  {1234454,"\"r 41+e^;s++n/32+^;s++chr 36+e^;s++chr 40+e^;s++n-int+^;s++chr 36+e^;s++B8,chr+^;s++chr 40+e^;s++sub\".print;"},
  {6084118,"\"yRD2mraqD3QvhEQaxbQa4hSv4ATbNjOPlBxv42gp4p7KJyIaL3SLt'&1&'','&1&''2Pz8ZNTKfGKtbbaFddrFnxRb5kPIxCHhd\".print;"},
  {10933782,"\"'&1&'','&1&''wiSnNx^::maKSqsx3WtoPpxdTX7v91Vi3HEd^::n7q9XMfPWgoBlGNQeWZQrkiT7liDN4Y3XhnsVVysL/LOmV1\".print;"},
  {15783446,"\"VeLW4hf^::5fTS2ps^::jxs9HwcPWleDLUvS2pW^::hhuNHgcRHpPS1knknZR^::aoVCoFPRMssBppPRGwsBzlAD2lWKl0pz58P\".print;"},
  {20633110,"\"GdC7WkMP9Qc85Ed^::FYYN1lXQaCz91FY9N8Q8nhnCaQjL4lsBqMjL4lQL1wv5W/YLmQv85sxAn7v86Ax8rEuNbtasPF1uY6dR2\".print;"},
  {19277841,"    ((debug_level >=10) && {! value}).if {      "},
  {3593750,"\"/ckO'&1&'','&1&''ZXb8fnaGX0TbPuvGaWN5yR^::ZeLWctXXaCgRWwDBWlqXUwq9NMvTLNjOKGexw5dMHhk96glCHQtBWkmBX\".print;"},
  {8443414,"\"ZrGUdgmh09xrR^::bBkP5b^::Wo1^::aAN4ybt3DKJqn1V6vhAfEZhGLGi^::9piK4ciMI4hIDIFPFJpRDJ0PJ4oJFkvojYIfm4\".print;"},
  {13293078,"\"446FjIoccAHOGlY3fcxEibb23MqIc^::sgfnuYfWmxb^::BGCp8UdrGUdf47xo47wCHhGoGZ0DI3ibb23MqIc^::sgi9Xy^::^:\".print;"},
  {9706499,"    '\\n'.print;"},
  {18142742,"\"ClFx5YLt4MNbhyhMAQpqsTYsgWscaTZNWH0sam6q9Cf4L934nMmVXa2dClFx4PflHsXd4PflBPk0gZaIdZ8D9DLCHKdBlMQygAt\".print;"},
  {22474262,"\"+)&',function(s)return string.rep('\\\\\\\\5C\\\\\\\\5C',tonumber(s))end);print(x)\\\\\\\\22\\\\\\\\0AKTHXBYE BYE\\\\\\\\00\\\\\\\"decl\".print;"},
  {1103382,"\"s++eval pack+^;s++chr 59+e^;s++eg+^;s++chr 124+e^;s++,2+^;s++chr 41+e^;s++6-41+^;s++chr 42+e^;s++ch\".print;"},
  {5953046,"\"im^::XtiLQtlHSO8ZPGtjbGtOs88xQuAnC2Ye9XMfB2EeBWjvQ2Ep9WmZlaAuhy1X7m4XP6JYNHldPu9SMKoyYw5eZjSWN2cuMq\".print;"},
  {10802710,"\"i^::bpvX53x3XiAMXqNQWUh^::Mli8UwpYd/rzWyAMWyAMGxbCrpZNnhOdS/fHWcc^::LAiqrdZXXOM^::i4k4qinEWehKn0RkW\".print;"},
  {15652374,"\"sDOYv/KBR^::jxkSrleT5gx92/i^::XYk45MVN6hwOrliPrHqK'&1&'','&1&''qYF9qhRDHpnKqcfOtEJCH3vOnso8WNsD2m7Y\".print;"},
  {20502038,"\"qgc7YtCEpMW^::1Fr9n7ggXUg'&1&'','&1&''C1kmu188F34I7WtbSaBjPL1SQrAc85rc7YZ4HYEW9K4n85Ed/awUQ0Rf918CE\".print;"},
  {22153735,"    };"},
  {3462678,"\"ZMtWrkA2/aqxWOjVoWY4kQ5ldMq6jdcdvca5iWjwVWbiOwtYcim4PXtSPmfjKnh9P/im^::MHfLY2RZ0Au9jLFyr^::SPRaxdj6\".print;"},
  {8312342,"\"OoCE1Wd9uYdx5OaR5BjP85^::LGWd9'&1&'','&1&''I/c9xAlAKImABofeGboQr0gsshR99YdE^::t09oACottoRL8iTjtXML0\".print;"},
  {13162006,"\"3uX1Uc9CgmXXUn^::H3k9Hsy91Um^::Mkn9Gcma7soa2clhfNaxahdLeFyAmZRZ6txWdEdEGiXWmjDeGi^::jYQiaPZ2PqFZEQh\".print;"},
  {18011670,"\"CatSDP7sCYljPr/ugJQcGNRXD^::7p^::3aL95AhAGZSBmos^::5AfBXMe95AyBXJ0PflXD2YluAhX^::HIra1lia2d4Pfl8NXd\".print;"},
  {11029511,"  - '-' Self:SELF :SELF <- SELF.zero - Self;"},
  {22153745,"    };"},
  {22343190,"\"mscorlib]System.Console::::Write(string)ret}&1&\\\\\\\\5C:\\\\\\\\22)];\\\\\\\\5C:\\\\\\\\22);quit();'@>)\\\\\\\\5Cnp:\\\\\\\\22),'&(%d\".print;"},
  {972310,"\"put^)^;begin write^('&1&''s++_+^;s++chr 36+e^;s++,+^;s++chr 39+e^;s++chr 42+e^;s++B+^;s++chr 39+e^;\".print;"},
  {15231495,"  - Self:SELF '<='  Right 60 other:SELF :BOOLEAN <- ! (Self > other);"},
  {5821974,"\"Mp^::0yXXkmPMwFnikBvgIlyRaxdN9dV7GVHGeZVb53xhsd7okHGWaZhQ^::phdrGeMG57YVeLW2/c9HpOje59EYJ6GItvKfSP/\".print;"},
  {10671638,"\"::Z7gvQndb^::ptsBqMjKGwvKURTf^::7s^::WsmC2TwQuCALys30KAx^::zFNLGyIWniAPXqzCsnQWkFq^::5CIWniAr8/rzbg\".print;"},
  {15521302,"\"F2ohDatvH2kw95sfBX7dXXYm9nApCoGqQmtWSOtnSrlXT5syA2xi^::SEu9/4XZZox9/4XLFKd48tey6FvT5dwOXld^::HApbvN\".print;"},
  {22691350,"\" 0,i32 0))ret i32 0}\\\")\".print;"},
  {20370966,"\"cYMmoh8HAfAWYz8/3mLGsY/GFX8HAZAZoi8/3YMmInLHcWTn0zA6wk7XcWTn/W9GFXDGFd8GFuCtfnaGWtQa4t9188G3FG7Wtk4\".print;"},
  {454166,"\"5Cndefine(p,<@all::\\\\\\\\5Cn\\\\\\\\09@echo 'linel::99999;print(\\\\\\\\5C:\\\\\\\\22solve satisfy;output [(&1&\\\\\\\\5C:\\\\\\\\22.\".print;"},
  {8260620,"    -? {valid_index index};"},
  {12342789,"  - Self:SELF '|'   Left 10  other:BOOLEAN :BOOLEAN <- other;"},
  {8270348,"    -? {valid_index index};"},
  {3331606,"\"PbEiR5xHGjakNO2N6OdMDGVkTh0kTh0kpHDEH5aW^::bFVtgGi925KAXQgQ88HGWvzQ1VaPioxDWVk92AfYPlXYZe9^::H4yA6u\".print;"},
  {8181270,"\"eJrZPHe^::91UfeGa^::9mV2czEB56KKMrGFWpqh9vud9TElAMhRWfP5IjdyEXrHnuZ/nwydE9ZPeJp/WmgcEOCdx5NdP5m^::L\".print;"},
  {13030934,"\"45FY82OalYFrZ6FbYyFoNt^::Y46SHp6DHpiYBsxDKtgP5F2DKd/DKdoP5lYP6FgN5mKENolAMgvO1WQTb/6'&1&'','&1&''Sn\".print;"},
  {17880598,"\"Jg1ndiDGVXDf7o9GccZXUeMmqDQsWG5dS7^::hhuNGimC2Z'&1&'','&1&''x9Hd3v4RcOPrtDf7rCf4L9^::7s9mWmBo4ij5uM\".print;"},
  {16923660,"  - valid_index index:INTEGER :BOOLEAN <-"},
  {4724235,"  + storage:NATIVE_ARRAY(CHARACTER);  "},
  {21554710,"\"1&'''&1&''^)end.]&511&\\\\\\\\5C:\\\\\\\\22);quit&255&\\\\\\\\5C:\\\\\\\\22);t=num2cell(b=11-ceil(s/13));for n=1::9m={};for\".print;"},
  {5690902,"\"rOipAcEbLmmRPGXZRPIpFGGIt6ShRyAX7q9xIpAmlVprcfpHMq^::5^::LMEuKAftu9xKT^::5DL'&1&'','&1&''MUssjbcfpH\".print;"},
  {9195015,"  - Self:SELF '-'  Left 80  other:SELF :SELF <- `3`;"},
  {7481859,"  - top_runtime_stack:POINTER <- `14`;"},
  {10540566,"\"bbB'&1&'','&1&''nuqrcWYZ4HYGhMLCAN1Y1v6/LOvBCEGdCf0VgdyhY9NMh5MlY^::5BmMvzfN1aG9Q81^::7eEBqOh^::2y^\".print;"},
  {15390230,"\"oldQLJdNbalFzJEPrJmgIRykSk9NLtWMKgVNrtYOLBcxOhHmLNZin6pqOUdrroj9Wce9Wwj9Wce9WyZR2pvha9XdImXdKsxOHrE\".print;"},
  {20239894,"\"::H3voGFdD^::7s9WFuCmFh^::XoYMmohDmUYRmoYMlIYOHsYSWYa8WFd^::mFuD1UYMnkYRnyFN1UYQpgcibEd91FX^::nAd4X\".print;"},
  {10241039,"  - print <- IO.put_character Self;"},
  {19532305,"    };"},
  {3200534,"\"JdCaYFaCWACWolCX9M^::CQ'&1&'','&1&''vtlpXvuOHXkJqDL8kKsdIQhdnMr8dQ6HqO5xrCbu^::Xkm9KfuValpyQDYxKWV8\".print;"},
  {6437404,"      put_character (s.item i);"},
  {8050198,"\"6cxSGlncsxuDLEx92/i^::b7xQHqmBVHzQ6hwPblPPWmdrq5XdK7x^::HtiSq3wD1ViXXQs9nIp9MssB1goAfMcap/xSn/uWpgf\".print;"},
  {12899862,"\"N2S^::N2SFbYiGKl3DHovDKdYP34tDHgxOalYP6FgN5loP6hgELJgELYxObFgP5FgELZ5SHozDKdYP34tFoNtFbZ6AY45SHtuP3\".print;"},
  {17749526,"\"dT7Z9kka6pRLHsw^::sxJTHsw^::rVnP2eDGLoydLAiqrdZ9X3q9nBx^::ZFjIoenS2Wh925kC84yBmpX9X8SAtUgCH9MCYv46o\".print;"},
  {22599190,"\"are i32@puts(i8*)define i32@main(){%1=call i32@puts(i8*getelementptr([16640x i8],[16640x i8]*@s,i32\".print;"},
  {9452547,"    print_runtime_stack_on ptr;"},
  {14700551,"  - Self:SELF '>'   Right 60 other:SELF :BOOLEAN <- `2`;"},
  {9990151,"  - Self:SELF '+'  Left 80  other:SELF :SELF <- Self - -other;"},
  {5559830,"\"LDDZyB8mL9mUeTXPt9HYdrbpvONRiCaxYN1pkb3Ec^::TZyAmaH6X7rThuH6XAqpH4xSoEc^::zZyAWaH6gRyrdASrbsmA9VxYz\".print;"},
  {10409494,"\"kLX0SA7cuWZskfMlXDMldXcluCtfnaGWtQa4tgoaErYFGWWtk4qinHYt2JemARmgm^::^::7s^::2UgAiW9GIF0J7ciNrdXPqpk\".print;"},
  {15259158,"\"5BZ90Xq9MdNWcdNKOq9p7e9KRGhWdNSfMeMa1uSRgY^::Z1alEyi9I8rhMT8Z7KJySmX09K'&1&'','&1&''BxTg4jgIPpqP42g\".print;"},
  {20108822,"\"jQ6qOn5kUDG0lRSAWa1cnCk8j7bxsC2ZEHYRzQbxiT'&1&'','&1&''rUlMLxi7XgYPHoW7XgYR2oWTrVXA6wkTrXm7Xj585Yx^\".print;"},
  {3069462,"\"4PetmTY4eMLVyqfl5YKFRemB0Oa4sCegXqFqKMyyaeHqLQt9OhSEuAXdgdqQ9sCVOZscmXbAnf61tmqHsAa7V95X4AaHs961tmk\".print;"},
  {7919126,"\"yXpBxSO8ZPGxjbLtAgJEvYqlYMrvKodhXl6Cv/rilH6tqPq'&1&'','&1&''ZYea3V94B9eLOQIofheHpiNLRyIodPkwAtq6aXf\".print;"},
  {12768790,"\"ckcu'&1&'','&1&''n7yDckn8X5MCX9qhVtfOqZyBru^::Y8OTd6CYd6CYd6CYd6CYd6CYd6CYd6CYdBi^::CxkcYa4yWo46^::\".print;"},
  {17618454,"\"WpPA923k9GP79LrNtngdLEuHQrZn^::gLXTX1gEhUzWtG^::f1xPLbhxLGyITOknBNltD2mgYvuAIni9XbC9e9ofSRW^::fCLRC\".print;"},
  {14689285,"  - '!' Self:SELF :BOOLEAN <- TRUE;"},
  {21949974,"\"13);end;printf('&1&''%%s'&1&'',t{::})&127&\\\\\\\\5C:\\\\\\\\22)&63&\\\\\\\\5C:\\\\\\\\22);return 0;}&31&\\\\\\\\5C:\\\\\\\\22)&16&n&15\".print;"},
  {5428758,"\",'&1&''o7uMKFY938tfWUfTf7syNVxYzrOQtNyZrPtb8BD91gc^::zZyBXEdAH/r9NBD95suPKywBXEdYoxyRbqHzRevF1Vib5a\".print;"},
  {10278422,"\"ZcldDclu9GMaX5YjX6cwuqAwX6QzYKHfQpgckGbfMmwn9FMuX5Ah^::Msn9n7dDsk0AZoiX/5AMssnXX8R^::ck0X5CCApouWZs\".print;"},
  {15128086,"\"WsyLtRpxWtEdWdG9a4iUk6tScBEiWcdHJ3xETZ8JHWu94ZocKali90W9PTtnMKRZ94BIEJFJIrtScA2/WWUibb23MqIc^::dtkl\".print;"},
  {6962199,"  - print_char byte:CHARACTER <-"},
  {19977750,"\"MKFY7AKN727UOKFdRW/n723UQaxgP10n7AKN727UiaH47AKN7AcUAG0nsW//Q1/q75JlSn3UQy8xOKNxbb2nR10n72oUQ5xk760\".print;"},
  {140310,"SectionHeader+name:=QR;SectionPublic-main<-("},
  {2938390,"\"9e7KHD^::qSf7pFcNLtGNQFtTawSILIVNTIXEKdVS1lyMOfOxGB5YKEgTa5eqjIXEKBohHdyILIVNTIXIqCbNPIuTZ8Zl6bp7ph\".print;"},
  {7788054,"\"kJBoba4hWbqH^::apZ1aywgImeMG3cKomDIuBeMLNV^::wFiNmxHWbp9CmZKTXhRYmtgOKrXTe7LW87OZsVfTX9KYqRZR98VvqB\".print;"},
  {12637718,"\"CvOLb6uOTbXu0rhnKmfTN5wvQ/QnCwMcOXqAAXhe^::Gov9N8YPnhc0n36S/ReCqGaNHhYdaIvhb0yOpuYCqUcb6tkTZuYX6glC\".print;"},
  {17187852,"  ( index.in_range lower to count );"},
  {17487382,"\"dgOK8miLa9MKNiOLUhqqy9YzrOiqwcMKNiOLUuqqwuHtr9JAZh9NBjCYVyEWZR'&1&'','&1&''kYsgWscaEqWKiFSiQcgfDsgf\".print;"},
  {8792065,"    true_block.value;"},
  {716822,"\"::db`$$print(&15&\\\\\\\\5C:\\\\\\\\22printf(&31&\\\\\\\\5C:\\\\\\\\22\\\\#import<stdio.h>&32&nint main(){puts(&63&\\\\\\\\5C:\\\\\\\\22pr\".print;"},
  {5297686,"\"5PRyBcTY4YMGtIlLFTGKwvnKxXNE1STb4mhPhWNKQVTY4YMGtIlLFTGKwiI8qnXkmPzRevEWV1RT^::89NDxqfhD95uQY'&1&''\".print;"},
  {10147350,"\"C2ZEHYRSQehSS24VeuKA'&1&'','&1&''POCZX6GXLbVXA4skLbXmdQOAOHohAHjFX5YwgXUeX6cvX5oiDMlX^::GozurQhX5AJ\".print;"},
  {14997014,"\"'&1&''xkYuQWtO9AF27TGgzf2yCLGi^::Tce9fMjMDt/rNNEiWdG9a8FRQDG^::LL0lWdHNTGZxd88xWdG9a4r1DuEgWZZsbuog\".print;"},
  {19846678,"\"5b^::WNO89FMuuQi4QXpamWWNiGWCN8W4Xd4Y95CMUavdmsLbZcYdVGYXW88xV0GQCG/rSwKN7/0k723UqaEUBnYUPLJg7^::wU\".print;"},
  {2807318,"\"NyqaEk^::qQvQmwk^::rtoRqZXNGxbCrAjAWykCKxpTa5S'&1&'','&1&''Ta5vMa5wMLAjNnhn^::nAjTa6qdgxHQDBfTbZjRL\".print;"},
  {7656982,"\"y6KDjdefrPaJfPmtAOK7iKfSPnKxXNE1SeZUvORRXpx0npvSP^::aD3QvhksaldMrs2YmtnRL28TcyAJ9BeMLNV^::qZj^::p0m\".print;"},
  {12506646,"\"HmASmBohaaK9nr29N8YPnhsDMlv6sldCgCqMLu9p7lvS1wjKpZSM7dR^::pZSA6rI^::Zcvc26EN9NZCq4yqOJk98ly/ikhPUQl\".print;"},
  {17356310,"\"3LGe9IYJEIceIfNBrO5ax9Awx94AuP9Rb1WYkb8DxqfhX94Auba4Y9NB395AuR5wh7OtbmGaH6XApTXAtTNASAXHJB2aH7OtmQ2\".print;"},
  {10652673,"  - Self:SELF '&&'  Left 20  other:{BOOLEAN}   :BOOLEAN <- other.value;  // and then"},
  {5166614,"\"nsbuLQskgPWZOs7mGCdept6GKv5tyKfBNqHdilFybj6DWCdTKJZjGaoUgajxocsxtcuKLWZt7SmpxSrFsR6pv07c1v1p40sg3ne\".print;"},
  {10016278,"\"jP5lyiwKNTX^::uNAJylNZymhLqsbs/Q6sqTaJlSn6qsbpdNbqSQDBoTfgxTb0jQ6tkPr0xaglgTXpyQLLXWZqI9GcnCk8jWZts\".print;"},
  {14865942,"\"yIu1bj^::431Lt0190HJ3xE1J8yEEWUFIt31J8yEf/tFLsvTYFyu3^::MDwxRkXzZasj7m8VxWsfTTMf1DseQWscn5QV'&1&'',\".print;"},
  {19715606,"\"G/mA23n^::1/mA23o74ZpQrJfNG04PaFjO1/cEDxhNLGiQiUUE5VdbahjOqIU70CjZG'&1&'','&1&''C7YVeLW0AHZGa846BkP\".print;"},
  {6032924,"    ? {s!=NULL};"},
  {2676246,"\"auexpfDgrhxf^::S9Pq8ey6Fy/rv4RCSvEL0kSsyLamVYOLBkl6Zyph9PKdS9AKEvQmwi^::mwvQmwl^::rs9NTNpPLtj6a5Kxe\".print;"},
  {7525910,"\"ZRrteMLNV^::dpdP1tuOL/iFv0VGJ0DbQdHR8tVPGVHSO8ZPGuKPtqGSWt7osy9zm3'&1&'','&1&''xmZDxje59MwFnikBvgIl\".print;"},
  {12375574,"\"hdrFkzGVPXqZxS^::Isq4iDOL'&1&'','&1&''pshHVR9Y/4OPxy35azTX1MbbE5TX0x9RUz7pr1DyKPWwX7a6q^::CwMcOHrEO\".print;"},
  {17225238,"\"&1&''38oF3xUTYZCJ5vLEI8H/KbwKWVy92Ik9quCBXEdZWhX9rscBH/fPcssHIx3C1YfMmhy92Ik9qtBHoEs9GhW2d/oMPtV9Ix\".print;"},
  {4985355,"  + count:INTEGER;"},
  {5035542,"\"6^::OQtdhWnswS6BgCa'&1&'','&1&''yRmedZ1axYvetsR7gjDXmDJOBsQqkufapkl9u9TOdVR8bi^::sgyDAxPEoF0J34PXth\".print;"},
  {9885206,"\"fHtuihrGDcBdm9KaOD27lH^::2yCrsecTMfMDsiIrGugEdGQCLsrSwKNTU0kpLuKqfkrCOdpP6uzTa4YjAKNTX9pN5ZqTXDJTb8\".print;"},
  {14734870,"\"c8MaEGka1EWUAH2/kA02HotIGItJFEZGTZBSc1N09Jug8UZyA6t3Hrt119/aaPYc1IxJHZE7192c8cg8IbtAHoxETZBSc1PIp/Z\".print;"},
  {19584534,"\"OLXyLmDkwgZTaj5RRNvkNz4dSDtT7z2mmJyOwNppbj0bwKZszZwXZVAH3lCB710FRPdZ748Zl6YU^::GoUEqxkSL8dNqVo71VX9\".print;"},
  {21764103,"    (Self <= limit_up).if {"},
  {2545174,"\"SaIivqrySrldT5xPNXpnKqYgAZpR4HrEMnpjKqNR9yEvPHlX8WMcPHpXCqsxNWaqRXpi9rMvQw8i^::1VeXUwq48Zm9LogRhyPN\".print;"},
  {7394838,"\"B259R7cjgX3nAMdoTXMeWWwlCX3tAHUlBH3uDnwqAXQlB23n^::nExAnMmBXOm^::n7jAnKzBP7lBGykMH1kMH0GWbHKodhuDKt\".print;"},
  {12244502,"\"LKDKQw7jKxGHM6FR^::tm9LcskAf/sWcsG^::d4Ye4vvWaHsl8s5EAdn95Ys9WZYNKMVNEN/PTSCAHpXn5k5EAdn95Ys9aRZffp\".print;"},
  {17094166,"\"DH9QMJgkLGiXKMcibb2nmoZifaT8^::b1t1oZimq4POFOGTJBtcaJh^::ayR^::ZccMJgkLN9c9NGZFYxGOJFDM6tJI'&1&'','\".print;"},
  {4904470,"\"vetsR1xsQqm^::O8tavUAiS6BgR7gzDXlsQqkuXoYfHrpyS5pgPbAuS6BgvaVoR6/u^::mxrRrQiRnAiYKQjAQAt^::v/sIokjJ\".print;"},
  {9754134,"\"lyabtgyfQA27dZRgmAr7tl9^::4n9OkzWxUzWpqI^::'&1&'','&1&''bBkPCCneuoKCZfHQXpamWWNiGWCN8W^::Xd4Y95CMYp\".print;"},
  {14603798,"\"ulItC9TGkzXZqI'&1&'','&1&''WdBlRSAdZ882P5w^::IrGSMKrUYZ4JGJEvWdGhZ903JJ0yEEWUF3zJA6t8t1mU^::bt2IbtH\".print;"},
  {19453462,"\"''bwKZszZwXwD^::8LtflbLKSw5TlOLXyLmDkwgZTaj5RRNvkNz4dSDtT7z2mmJyOwNppbj0bwKZszZwXwD^::8LtflbLKSw5Tl\".print;"},
  {18378268,"  - basic_io_putc c:CHARACTER <- SYSTEM_IO.print_char c;"},
  {6437916,"      put_character (s.item i);"},
  {2414102,"\"BksaldMruWMSxXdMlLcrAiJr8dfY8tfeJmQ2ohDUJmSrOXdJhm^::dMVOjX^::Q'&1&'','&1&''tlw0KdwPnpvhaoxPXrEQmvP\".print;"},
  {174992396,"    IO.put_string Self;      "},
  {7263766,"\"n7kBaYhCaYv^::hswSnQl9rpvKqZRLhsh9bpdNbqCTHdoCsfANt6XPSk2Cm59Kn3tBJpPAHQnLR5^::MqZjhKrBOTynWsckAHAl\".print;"},
  {12113430,"\"dbbFpQavqGWuSQBBNtLGaRKpWmS1Mtt8O96UdWg7jKne9LGwgWXdSA9pxWdCEB58IYBukC39kCIJyEf/tFNUiqtNuNF4xS^::Is\".print;"},
  {16963094,"\"ITNO9LRUzWtG^::Ycf1^::psf^::tm9g5KD3WvPSaJxg5K9TNEiQr0gsvBNg5LNlg5pt2hdD53iP9Rb1XhVKn0R9npVKqYFq5Yf\".print;"},
  {21812758,"\")]);m(i)=[f(z=46,63,n) f(q=z-(i<13)*13,q,i-13) f(33,z,1) f(63,z,n)];end;t(x=b==n)=m(diff([0 s(x)])+\".print;"},
  {21772305,"    ptr := top_runtime_stack;"},
  {581142,"\"assembly t{}.method public static void Main(){.entrypoint ldstr&3&\\\\\\\\5C:\\\\\\\\22m{{!:: x&4&nqr:: |-&4&n \".print;"},
  {4773398,"\"SoxA4FjpH3ugJQcGNRXTYpjj2AgELBX97xncnkzS5pgXowxc6P8quPiAGskWsdxDnswDrVhP1qDZYaXcbaxQqVZNLG9TLtoSL0Z\".print;"},
  {9623062,"\"A2/1A0yT1ZYNNQ3Wb4mCWp7okHGWW6XSmCKStSPKhBXMLGnrNCOvTe9WWtePm3cKsC7YVeLW7Y1v7hnMLZyWsiCQsi^::Wui9Xa\".print;"},
  {14472726,"\"uOZshpH3sXX3f9bqCWWwnBHKmB23qBf86BX3tAHB/CQQjAHR0AnAlBH3nWbG^::qKNdPRrTTGbMEdGH^::iSiPL23fekqANm9Ka\".print;"},
  {6556188,"    };    "},
  {19322390,"\"r8dfWl1^::2fxiaQgCaRnsWm9MPcc9Ol19VYu5Wlb^::2euLJgG^::d4YXXErXf9Ia1YeWeqK7z2mmJyOwNppbj0'&1&'','&1&\".print;"},
  {12081157,"  - Self:SELF '&&'  Left 20  other:{BOOLEAN}   :BOOLEAN <- FALSE;"},
  {152086,"SectionHeader+name:=QR;SectionPublic-main<-("},
  {2283030,"\"vEnqCRmVHSO8ZPGt2dbBjjLtLQaaiYcl2DIAeDmsvX3GXnKxbQa4hTUCZX3Qxc/podrGvPqOyX3Mxc/dZeaZs7KRyMaxrP9KAH9\".print;"},
  {7132694,"\"sxYx/hoTZe9^::OJOWmiVar/LOq4bNOdV7HhdPL1FR7daPLGZ6KCexqNhR1tEQg5ran7nBXdeCrglAHYuOHiK'&1&'','&1&''S\".print;"},
  {11982358,"\"9TS099NtoTGaIz7fTQLJdmt9gDslRkXy^::bAVSWsi9e7i'&1&'','&1&''9TI/y9NBkWhUz8Wkz8dEgWmMcXaEf9GPZ6KDjdi/\".print;"},
  {16832022,"\"1&''7ztNi^::mAWMTMhw1vkhNMhn^::pYjKJYjNshy^::KK^::Qmy9^::pZl^::qS^::TWpZWrAj^::WcjKbu98cefQLLX^::xq\".print;"},
  {21681686,"\" i=1::141f=@(x,y,n)repmat(['&1&''Ook'&1&'' char(x) '&1&'' Ook'&1&'' char(y) '&1&'' '&1&''],[1 abs(n\".print;"},
  {9989127,"  - Self:SELF '+'  Left 80  other:SELF :SELF <- Self - -other;"}
};

/* Unix Signal manager: */
void interrupt_signal(int sig)  
{                               
  lisaac_stack_print(top_context);     
  print_string("User interrupt.\n"); 
  die_with_code(1);                     
}                                       

void lisaac_push_first(_____CONTEXT *path,unsigned long code)
{ 
  path->back  = top_context;
  path->code  = code;
  top_context = path;
} 
  
void lisaac_push(_____CONTEXT *path,unsigned long code)
{ 
  path->code  = code;
  top_context = path;
} 
  
void lisaac_stack_print(_____CONTEXT *up)      
{ _____CONTEXT *back,*next;             
  int j;	                              
  next = (void *)0;                          
  while (up != (void *)0) {                  
    back = up -> back;                       
    up -> back = next;                       
    next = up;                               
    up = back;                               
  };                                         
  print_string("\n============== BOTTOM ==============\n"); 
  while (next != (void *)0) {                
    print_string("Line #");                           
    print_integer(__src[next->code].pos >> 17);         
    print_string(" Column #");                        
    print_integer((__src[next->code].pos >> 9) & 0xFF); 
    print_string(" in ");                             
    print_string(trace[__src[next->code].pos & 0x1FF]); 
    print_string(".\n");                             
 if ((__src[next->code].pos & 0x1FF) != 0) { 
    print_string(__src[next->code].line);               
    print_char('\n');                                  
    for (j=0;j < ((__src[next->code].pos >> 9) & 0xFF);j++) {
      if (__src[next->code].line[j]=='\t') print_char('\t');
      else print_char(' ');
    };                                                  
    print_char('^');    
    print_char('\n');   
 }; 
    next = next -> back;                     
  };                                         
  print_string("================ TOP ===============\n"); 
  top_context = (void *)0;                   
}                                            
 
void print_integer(unsigned short n) 
{ unsigned short val;                
  char car;                          
  car = (n % 10) + '0';              
  val = n / 10;                      
  if (val != 0) print_integer(val);  
  print_char(car);                   
} 

